In [5]:
import Capital_pressure 
from Capital_pressure import *
import pandas as pd
from sodapy import Socrata
import numpy as np
import plotly.express as px
import yfinance as yf

In [20]:
all_tickers = []
for asset_type in TICKER.keys():
    all_tickers = all_tickers + TICKER[asset_type]
all_tickers

['NVDA',
 'AAPL',
 'MSFT',
 'AMZN',
 'GOOG',
 'AVGO',
 'META',
 'TSLA',
 'BRK-B',
 'EUR=X',
 'JPY=X',
 'GBP=X',
 'CAD=X',
 'CHF=X',
 'BTC-USD',
 'ETH-USD',
 'BNB-USD',
 'XRP-USD',
 'SOL-USD',
 'BZT=F',
 'MCL=F',
 'GC=F',
 'HG=F',
 'NG=F',
 'ZC=F',
 'ZS=F',
 'SI=F',
 'KE=F',
 'KC=F',
 'TLT',
 'IEF',
 'MBB',
 'EMB',
 'SHY',
 'SDEU.L',
 '2561.T',
 'IGLT.L']

In [21]:

df = yf.download(tickers = all_tickers, start = '2020-01-01')
df

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_40095/1415778321.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers = all_tickers, start = '2020-01-01')
[*********************100%***********************]  37 of 37 completed

Price        Close                                                  \
Ticker      2561.T        AAPL        AMZN        AVGO     BNB-USD
Date
2020-01-01     NaN         NaN         NaN         NaN   13.689083
2020-01-02     NaN   72.400520   94.900497   27.735554   13.027011
2020-01-03     NaN   71.696632   93.748497   27.030096   13.660452
2020-01-04     NaN         NaN         NaN         NaN   13.891512
2020-01-05     NaN         NaN         NaN         NaN   14.111019
...            ...         ...         ...         ...         ...
2026-03-06  2099.0  257.459991  213.210007  330.480011  627.273438
2026-03-07     NaN         NaN         NaN         NaN  620.066284
2026-03-08     NaN         NaN         NaN         NaN  612.038879
2026-03-09  2093.0  259.880005  213.490005  345.750000  634.500366
2026-03-10  2100.0         NaN         NaN         NaN  646.599060

Price                                                         ...  \
Ticker           BRK-B       BTC-USD BZT=F    CAD=X    CHF=X  ...
Date                                                          ...
2020-01-01         NaN   7200.174316   NaN  1.30020  0.96720  ...
2020-01-02  228.389999   6985.470215  0.00  1.29730  0.96750  ...
2020-01-03  226.179993   7344.884277  0.00  1.29830  0.97120  ...
2020-01-04         NaN   7410.656738   NaN      NaN      NaN  ...
2020-01-05         NaN   7411.317383   NaN      NaN      NaN  ...
...                ...           ...   ...      ...      ...  ...
2026-03-06  498.980011  68136.492188  0.00  1.36699  0.78066  ...
2026-03-07         NaN  67272.593750   NaN      NaN      NaN  ...
2026-03-08         NaN  65969.781250   NaN      NaN      NaN  ...
2026-03-09  497.200012  68402.382812   NaN  1.36021  0.78122  ...
2026-03-10         NaN  70923.039062 -0.75  1.35798  0.77573  ...

Price            Volume                                                       \
Ticker             NVDA SDEU.L        SHY     SI=F       SOL-USD         TLT
Date
2020-01-01          NaN    NaN        NaN      NaN           NaN         NaN
2020-01-02  237536000.0   14.0  2665200.0      2.0           NaN  11034100.0
2020-01-03  205384000.0  410.0  2039900.0     83.0           NaN  12366000.0
2020-01-04          NaN    NaN        NaN      NaN           NaN         NaN
2020-01-05          NaN    NaN        NaN      NaN           NaN         NaN
...                 ...    ...        ...      ...           ...         ...
2026-03-06  189021900.0    NaN  5750000.0    597.0  3.739561e+09  58136900.0
2026-03-07          NaN    NaN        NaN      NaN  1.916017e+09         NaN
2026-03-08          NaN    NaN        NaN      NaN  2.686951e+09         NaN
2026-03-09  176547500.0  113.0  4899200.0      NaN  4.216355e+09  52465300.0
2026-03-10          NaN    NaN        NaN  12833.0  4.129255e+09         NaN

Price
Ticker             TSLA     XRP-USD      ZC=F     ZS=F
Date
2020-01-01          NaN  1041134003       NaN      NaN
2020-01-02  142981500.0  1085351426  103987.0   2217.0
2020-01-03  266677500.0  1270017043  125931.0   2272.0
2020-01-04          NaN   999331594       NaN      NaN
2020-01-05          NaN  1168067557       NaN      NaN
...                 ...         ...       ...      ...
2026-03-06   64054600.0  2371949533     385.0    370.0
2026-03-07          NaN  1142130992       NaN      NaN
2026-03-08          NaN  1647984917       NaN      NaN
2026-03-09   66821300.0  2485298247       NaN      NaN
2026-03-10          NaN  2370369792   43251.0  23781.0

[2261 rows x 185 columns]

Phase 1 — Complete current work (nearly done)
+ ✓ SP500 three actor analysis
+ ✓ Robustness tests
+ → Add non-reportables
+ → Run same analysis on 10Y Treasury and VIX
+ add ETF FLow Data
+ Use price-implied positioning

Phase 2 — Cross asset positioning matrix
+ → Build unified positioning dataset across 6 instruments
+ → Compute cross-asset positioning divergence scores
+ → Test whether bond positioning predicts equity returns
+ → Test whether VIX positioning predicts equity returns

Phase 3 — Full container model
+ → Map capital flow proxies across asset classes
+ → Build rolling flow score per asset
+ → Test whether flow exhaustion in one predicts inflow to another
+ → This is the original theory fully realised

# Maps

In [ ]:
INSTRUMENT_MAP = {
    # S&P 500 — all variants map to same instrument
    'E-MINI S&P 500 STOCK INDEX - CHICAGO MERCANTILE EXCHANGE': 'SP500',
    'E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE':             'SP500',
    'S&P 500 Consolidated - CHICAGO MERCANTILE EXCHANGE':       'SP500',
    
}

In [335]:
TICKER_MAP = {
    'SP500':   '^GSPC',
    'NASDAQ':  '^NDX',
    'EURUSD':  'EURUSD=X',
    'RAND':    'ZAR=X',
    'BITCOIN': 'BTC-USD',
}

# Dating Downloading

In [298]:
def download_cot_data(years, report_type='combined'):
    """
    Downloads raw CFTC Traders in Financial Futures (TFF) data.

    Args:
        years       : list of int — e.g. [2020, 2021, 2022]
        report_type : 'futures' or 'combined' (futures + options)

    Returns:
        pd.DataFrame — raw unmodified TFF data
    """
    prefix_map = {
        'futures':  'fut_fin_xls',
        'combined': 'com_fin_xls',
    }
    assert report_type in prefix_map, f"report_type must be one of {list(prefix_map.keys())}"
    prefix = prefix_map[report_type]

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        'Referer':    'https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm',
    }

    dfs = []
    for year in years:
        url = f"https://www.cftc.gov/files/dea/history/{prefix}_{year}.zip"
        print(f"Fetching {report_type} COT {year} from {url}...")
        try:
            response = requests.get(url, headers=headers, timeout=30)
            response.raise_for_status()
            zf  = zipfile.ZipFile(io.BytesIO(response.content))
            xls = zf.open(zf.namelist()[0]).read()
            dfs.append(pd.read_excel(io.BytesIO(xls), engine='xlrd'))
            print(f"  ✓ {year} fetched successfully")
        except requests.HTTPError as e:
            print(f"  ✗ HTTP error for {year}: {e}")
        except zipfile.BadZipFile:
            print(f"  ✗ Bad zip file for {year}")
        except Exception as e:
            print(f"  ✗ Unexpected error for {year}: {e}")

    if not dfs:
        raise RuntimeError("No data fetched — check years and network connection")

    return pd.concat(dfs, ignore_index=True)

# Data cleaning

+ Dealer — financial institutions/dealers (often on the other side of client trades)
+ Asset_Mgr — institutional investors like pension funds, mutual funds
+ Lev_Money — leveraged money (hedge funds, CTAs)
+ Other_Rept — other reportable traders
+ NonRept — non-reportable (small traders below reporting thresholds)
+ Traders - it's counting number of traders, knowing 47 dealers are long tells you less than knowing their total position size
+ Concentration Report - Shows what % of open interest the top 4 and top 8 traders control

In [300]:
def find_dominant_contracts(df, instrument_name):
    """
    For a given instrument, shows which contract names exist,
    how many weeks each was dominant, and the date range of dominance.
    
    Use this BEFORE updating INSTRUMENT_MAP to understand what to include.
    
    Args:
        df              : raw COT DataFrame
        instrument_name : str — search term e.g. 'EURO FX', 'NASDAQ', 'BITCOIN'
        top_n           : int — how many contracts to show
    
    Returns:
        pd.DataFrame — contract names, dominance count, date ranges
    """
    # Find all contracts matching the search term and print the variant names
    df_filtered = df[df['Market_and_Exchange_Names'].str.contains(instrument_name)]
    df_filtered = df_filtered[['Market_and_Exchange_Names', 'Report_Date_as_MM_DD_YYYY', 'Open_Interest_All']]
    df_filtered_pivot = df_filtered.pivot_table(
    index='Report_Date_as_MM_DD_YYYY',
    columns='Market_and_Exchange_Names',
    values='Open_Interest_All',
    aggfunc='first' ) # in case of duplicates, take first

    
    variant_names = (df_filtered_pivot.columns.values.tolist())
    print(f"Variants: For {instrument_name}: ") 
    for i in variant_names:
        print(i)
    if len(variant_names) == 0:
        print('Probably Searched Wrong')

    df_filtered_pivot['Total'] = df_filtered_pivot.sum(axis=1, )

    df_filtered_pivot_proportions = df_filtered_pivot.div(df_filtered_pivot['Total'], axis=0) * 100
    df_filtered_pivot_proportions = df_filtered_pivot_proportions.drop(columns='Total')
    return px.line(df_filtered_pivot_proportions)

In [301]:
def clean_financial_cot_data(df, instrument_map):
    ''' Dealer — financial institutions/dealers (often on the other side of client trades)
        Asset_Mgr — institutional investors like pension funds, mutual funds
        Lev_Money — leveraged money (hedge funds, CTAs)
        Other_Rept — other reportable traders
        NonRept — non-reportable (small traders below reporting thresholds)
        Traders - it's counting number of traders, knowing 47 dealers are long tells you less than knowing their total position size
        Concentration Report - Shows what % of open interest the top 4 and top 8 traders control'''
    
    # take only the columns we need
    df = df[['Market_and_Exchange_Names', 
    'Report_Date_as_MM_DD_YYYY', 
    'Open_Interest_All', 
    'Dealer_Positions_Long_All', 'Dealer_Positions_Short_All',
    'Asset_Mgr_Positions_Long_All','Asset_Mgr_Positions_Short_All',
    'Lev_Money_Positions_Long_All', 'Lev_Money_Positions_Short_All'
    ]]


    df['Report_Date_as_MM_DD_YYYY'] = pd.to_datetime(df['Report_Date_as_MM_DD_YYYY'])
    df = df.sort_values('Report_Date_as_MM_DD_YYYY')

    df['Instrument'] = df['Market_and_Exchange_Names'].map(instrument_map)
    df = df[df['Instrument'].notna()].copy()

    cols_to_sum = df.columns.values.tolist()
    cols_to_sum.remove('Market_and_Exchange_Names')
    cols_to_sum.remove('Report_Date_as_MM_DD_YYYY')
    cols_to_sum.remove('Instrument')
    df = (
    df.groupby(['Instrument', 'Report_Date_as_MM_DD_YYYY'])[cols_to_sum]
    .sum()
    .reset_index()
    )


    return df

In [302]:
cot_raw = download_cot_data([2020, 2021, 2022, 2023, 2024, 2025, 2026])

Fetching combined COT 2020 from https://www.cftc.gov/files/dea/history/com_fin_xls_2020.zip...
  ✓ 2020 fetched successfully
Fetching combined COT 2021 from https://www.cftc.gov/files/dea/history/com_fin_xls_2021.zip...
  ✓ 2021 fetched successfully
Fetching combined COT 2022 from https://www.cftc.gov/files/dea/history/com_fin_xls_2022.zip...
  ✓ 2022 fetched successfully
Fetching combined COT 2023 from https://www.cftc.gov/files/dea/history/com_fin_xls_2023.zip...
  ✓ 2023 fetched successfully
Fetching combined COT 2024 from https://www.cftc.gov/files/dea/history/com_fin_xls_2024.zip...
  ✓ 2024 fetched successfully
Fetching combined COT 2025 from https://www.cftc.gov/files/dea/history/com_fin_xls_2025.zip...
  ✓ 2025 fetched successfully
Fetching combined COT 2026 from https://www.cftc.gov/files/dea/history/com_fin_xls_2026.zip...
  ✓ 2026 fetched successfully

In [315]:
get_dominant_contracts(cot_raw, 'S&P 500')

Variants: For S&P 500:
ADJUSTED INT RATE S&P 500 TOTL - CHICAGO MERCANTILE EXCHANGE
E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE
E-MINI S&P 500 STOCK INDEX - CHICAGO MERCANTILE EXCHANGE
MICRO E-MINI S&P 500 INDEX - CHICAGO MERCANTILE EXCHANGE
S&P 500 ANNUAL DIVIDEND INDEX - CHICAGO MERCANTILE EXCHANGE
S&P 500 Consolidated - CHICAGO MERCANTILE EXCHANGE
S&P 500 QUARTERLY DIVIDEND IND - CHICAGO MERCANTILE EXCHANGE
S&P 500 STOCK INDEX - CHICAGO MERCANTILE EXCHANGE
S&P 500 TOTAL RETURN INDEX - CHICAGO MERCANTILE EXCHANGE

In [303]:
cot_clean = clean_financial_cot_data(cot_raw, INSTRUMENT_MAP)
cot_clean

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/588470530.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Instrument,Report_Date_as_MM_DD_YYYY,Open_Interest_All,Dealer_Positions_Long_All,Dealer_Positions_Short_All,Asset_Mgr_Positions_Long_All,Asset_Mgr_Positions_Short_All,Lev_Money_Positions_Long_All,Lev_Money_Positions_Short_All
0,SP500,2020-01-07,4207762,260030,1004874,1834110,584813,347779,600716
1,SP500,2020-01-14,4350542,204757,1051362,1888684,569086,302283,590228
2,SP500,2020-01-21,4396862,223857,1084396,1919318,582881,315655,630592
3,SP500,2020-01-28,4396047,224009,1128277,1864796,591326,314865,588760
4,SP500,2020-02-04,4291280,195894,1145593,1845717,557080,304941,562861
...,...,...,...,...,...,...,...,...,...
317,SP500,2026-02-03,5203392,271091,1583677,2236165,383666,255229,1129758
318,SP500,2026-02-10,5265254,275823,1613982,2213875,374490,237843,1066249
319,SP500,2026-02-17,5402008,269010,1585381,2319002,384188,228998,1130269
320,SP500,2026-02-24,5396209,277536,1616521,2390417,381393,225031,1155076
321,SP500,2026-03-03,5665811,260798,1708366,2367775,377381,306121,1099489

# Calulcations and stuff

In [358]:
import yfinance as yf
def process_COT(df_cot, instrument, start_date, end_date):
    """
    Args:
        df_cot      : cleaned COT dataframe (output of clean_cot_data())
        instrument  : str — e.g. 'SP500'
        start_date  : str — e.g. '2020-01-01'
        end_date    : str — e.g. '2022-12-31'
    """

    df_clean = df_cot[
    (df_cot['Instrument'] == instrument) &
    (df_cot['Report_Date_as_MM_DD_YYYY'] >= start_date) &
    (df_cot['Report_Date_as_MM_DD_YYYY'] <= end_date)
    ].copy()

    df_clean["Dealer Net"] = df_clean['Dealer_Positions_Long_All'] - df_clean['Dealer_Positions_Short_All']
    df_clean["Asset Manager Net"] = df_clean['Asset_Mgr_Positions_Long_All'] - df_clean['Asset_Mgr_Positions_Short_All'] 
    df_clean["Levered Net"] = df_clean['Lev_Money_Positions_Long_All'] - df_clean['Lev_Money_Positions_Short_All']

    df_clean["Dealer Long Proportion"] = df_clean['Dealer_Positions_Long_All']/df_clean['Open_Interest_All']
    df_clean["Asset Manager Long Proportion"] = df_clean['Asset_Mgr_Positions_Long_All']/df_clean['Open_Interest_All']
    df_clean["Levered Long Proportion"] = df_clean['Lev_Money_Positions_Long_All']/df_clean['Open_Interest_All']

    df_clean["Dealer Short Proportion"] = df_clean['Dealer_Positions_Short_All']/df_clean['Open_Interest_All']
    df_clean["Asset Manager Short Proportion"] = df_clean['Asset_Mgr_Positions_Short_All']/df_clean['Open_Interest_All']
    df_clean["Levered Short Proportion"] = df_clean['Lev_Money_Positions_Short_All']/df_clean['Open_Interest_All']


    df_clean["Dealer Crowding"] = (df_clean['Dealer_Positions_Long_All']+df_clean['Dealer_Positions_Short_All'])/df_clean['Open_Interest_All']
    df_clean["Asset Manager Crowding"] = (df_clean['Asset_Mgr_Positions_Long_All']+df_clean['Asset_Mgr_Positions_Short_All'])/df_clean['Open_Interest_All']
    df_clean["Levered Manager Crowding"] = (df_clean['Lev_Money_Positions_Long_All']+df_clean['Lev_Money_Positions_Short_All'])/df_clean['Open_Interest_All']

    ticker = TICKER_MAP[instrument]
    spy = yf.download(tickers=ticker, start=start_date, end=end_date)['Close']

    spy_tuesday = spy[spy.index.dayofweek == 1]
    spy_tuesday.index.name = 'Report_Date_as_MM_DD_YYYY'
    spy_tuesday.name = 'Price_Close'  # rename the Series before merging

    df_clean_merged = df_clean.merge(spy_tuesday, on='Report_Date_as_MM_DD_YYYY', how='inner')
    df_clean_merged = df_clean_merged.rename(columns={ticker: 'Price_Close'})
    df_clean_merged

    return df_clean_merged

In [359]:
processed_cot_1 = process_COT(cot_clean, 'SP500', '2020-01-01', '2023-01-01')
processed_cot_1

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/2219192598.py:35: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

,Instrument,Report_Date_as_MM_DD_YYYY,Open_Interest_All,Dealer_Positions_Long_All,Dealer_Positions_Short_All,Asset_Mgr_Positions_Long_All,Asset_Mgr_Positions_Short_All,Lev_Money_Positions_Long_All,Lev_Money_Positions_Short_All,Dealer Net,...,Dealer Long Proportion,Asset Manager Long Proportion,Levered Long Proportion,Dealer Short Proportion,Asset Manager Short Proportion,Levered Short Proportion,Dealer Crowding,Asset Manager Crowding,Levered Manager Crowding,Price_Close
0,SP500,2020-01-07,4207762,260030,1004874,1834110,584813,347779,600716,-744844,...,0.061798,0.435887,0.082652,0.238814,0.138984,0.142764,0.300612,0.574872,0.225416,3237.179932
1,SP500,2020-01-14,4350542,204757,1051362,1888684,569086,302283,590228,-846605,...,0.047065,0.434126,0.069482,0.241662,0.130808,0.135668,0.288727,0.564934,0.205149,3283.149902
2,SP500,2020-01-21,4396862,223857,1084396,1919318,582881,315655,630592,-860539,...,0.050913,0.436520,0.071791,0.246630,0.132567,0.143419,0.297542,0.569087,0.215210,3320.790039
3,SP500,2020-01-28,4396047,224009,1128277,1864796,591326,314865,588760,-904268,...,0.050957,0.424198,0.071625,0.256657,0.134513,0.133929,0.307614,0.558711,0.205554,3276.239990
4,SP500,2020-02-04,4291280,195894,1145593,1845717,557080,304941,562861,-949699,...,0.045649,0.430109,0.071061,0.266958,0.129817,0.131164,0.312608,0.559925,0.202225,3297.590088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,SP500,2022-11-29,3985474,470155,539081,1177067,603910,160618,656447,-68926,...,0.117967,0.295339,0.040301,0.135261,0.151528,0.164710,0.253229,0.446867,0.205011,3957.629883
151,SP500,2022-12-06,4033628,470108,499536,1138422,587166,154014,667862,-29428,...,0.116547,0.282233,0.038182,0.123843,0.145568,0.165574,0.240390,0.427800,0.203756,3941.260010
152,SP500,2022-12-13,4269726,441778,454772,1152355,569503,136279,699467,-12994,...,0.103468,0.269890,0.031918,0.106511,0.133382,0.163820,0.209978,0.403271,0.195738,4019.649902
153,SP500,2022-12-20,3444320,220835,443704,1153979,624632,182152,443802,-222869,...,0.064116,0.335038,0.052885,0.128822,0.181351,0.128850,0.192938,0.516390,0.181735,3821.620117
154,SP500,2022-12-27,3355691,236508,414792,1146820,614305,161832,458035,-178284,...,0.070480,0.341754,0.048226,0.123609,0.183064,0.136495,0.194088,0.524817,0.184721,3829.250000

# Diagnostics

In [346]:
def _print_data_quality(df):
    
    print("=" * 50)
    print("SECTION 1 — DATA QUALITY")
    print("=" * 50)
    
    # Basic shape
    print(f"\nRows       : {len(df)}")
    print(f"Date Range : {df['Report_Date_as_MM_DD_YYYY'].min().date()} → {df['Report_Date_as_MM_DD_YYYY'].max().date()}")
    
    # Missing weeks
    all_tuesdays = pd.date_range(
        start=df['Report_Date_as_MM_DD_YYYY'].min(),
        end=df['Report_Date_as_MM_DD_YYYY'].max(),
        freq='W-TUE'
    )
    missing = all_tuesdays.difference(df['Report_Date_as_MM_DD_YYYY'])
    print(f"\nExpected Weeks : {len(all_tuesdays)}")
    print(f"Missing Weeks  : {len(missing)}")
    if len(missing) > 0:
        print(f"Missing Dates  : {list(missing.date)}")
    
    # Null check
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if nulls.empty:
        print(f"\nNulls : None ✓")
    else:
        print(f"\nNulls Found :\n{nulls}")
    
    # OI spike detection
    oi_mean = df['Open_Interest_All'].mean()
    oi_std  = df['Open_Interest_All'].std()
    spikes  = df[df['Open_Interest_All'] > oi_mean + 2 * oi_std]
    print(f"\nOI Spikes (>2 std devs) : {len(spikes)}")
    if len(spikes) > 0:
        print(spikes[['Report_Date_as_MM_DD_YYYY', 'Open_Interest_All']].to_string(index=False))
    
    print()

In [349]:
def _print_descriptives(df):
    
    print("=" * 50)
    print("SECTION 2 — DESCRIPTIVE STATISTICS")
    print("=" * 50)
    
    # Actor net positions
    actors = {
        'Dealer':       'Dealer Net',
        'Asset Manager':'Asset Manager Net',
        'Lev Money':    'Levered Net',
    }
    
    print("\n--- Actor Net Positions ---")
    for name, col in actors.items():
        print(f"\n{name}")
        print(f"  Mean : {df[col].mean():>12,.0f}")
        print(f"  Max  : {df[col].max():>12,.0f}")
        print(f"  Min  : {df[col].min():>12,.0f}")
        print(f"  Std  : {df[col].std():>12,.0f}")
    
    # Average crowding per actor
    print("\n--- Average Crowding (% of OI) ---")
    crowding = {
        'Dealer':        'Dealer Crowding',
        'Asset Manager': 'Asset Manager Crowding',
        'Lev Money':     'Levered Manager Crowding',
    }
    for name, col in crowding.items():
        print(f"  {name:<20}: {df[col].mean()*100:.1f}%")
    
    # Structural net check
    print("\n--- Structural Net Check ---")
    df['Total Net'] = df['Dealer Net'] + df['Asset Manager Net'] + df['Levered Net']
    print(f"  Total Net Mean : {df['Total Net'].mean():>12,.0f}  (should be near zero)")
    print(f"  Total Net Std  : {df['Total Net'].std():>12,.0f}")
    
    print()

In [350]:
def _print_descriptives(df):
    
    print("=" * 50)
    print("SECTION 2 — DESCRIPTIVE STATISTICS")
    print("=" * 50)
    
    # Actor net positions
    actors = {
        'Dealer':       'Dealer Net',
        'Asset Manager':'Asset Manager Net',
        'Lev Money':    'Levered Net',
    }
    
    print("\n--- Actor Net Positions ---")
    for name, col in actors.items():
        print(f"\n{name}")
        print(f"  Mean : {df[col].mean():>12,.0f}")
        print(f"  Max  : {df[col].max():>12,.0f}")
        print(f"  Min  : {df[col].min():>12,.0f}")
        print(f"  Std  : {df[col].std():>12,.0f}")
    
    # Average crowding per actor
    print("\n--- Average Crowding (% of OI) ---")
    crowding = {
        'Dealer':        'Dealer Crowding',
        'Asset Manager': 'Asset Manager Crowding',
        'Lev Money':     'Levered Manager Crowding',
    }
    for name, col in crowding.items():
        print(f"  {name:<20}: {df[col].mean()*100:.1f}%")
    
    # Structural net check
    print("\n--- Structural Net Check ---")
    df['Total Net'] = df['Dealer Net'] + df['Asset Manager Net'] + df['Levered Net']
    print(f"  Total Net Mean : {df['Total Net'].mean():>12,.0f}  (should be near zero)")
    print(f"  Total Net Std  : {df['Total Net'].std():>12,.0f}")
    
    print()

In [353]:
def _print_correlations(df):
    
    print("=" * 50)
    print("SECTION 3 — CORRELATIONS VS PRICE LEVELS")
    print("=" * 50)
    
    actors = {
        'Dealer':       'Dealer Net',
        'Asset Manager':'Asset Manager Net',
        'Lev Money':    'Levered Net',
    }
    
    for name, col in actors.items():
        print(f"\n{name}")
        print(f"  {'Lag':<6} {'Corr':>8} {'PValue':>10} {'Sig':>6}")
        print(f"  {'-'*34}")
        for lag in range(0, 13):
            aligned = df[[col, 'Price_Close']].copy()
            aligned[col] = aligned[col].shift(lag)
            aligned = aligned.dropna()
            corr, pvalue = stats.pearsonr(aligned[col], aligned['Price_Close'])
            sig = '✓' if pvalue < 0.05 else ''
            print(f"  {lag:<6} {corr:>8.3f} {pvalue:>10.4f} {sig:>6}")
    
    print()

In [365]:
def _print_forward_returns(df):
    
    print("=" * 50)
    print("SECTION 4 — FORWARD RETURN ANALYSIS")
    print("=" * 50)
    
    # Compute forward returns
    df = df.copy()
    df['Fwd_4wk_Return']  = df['Price_Close'].pct_change(4).shift(-4)
    df['Fwd_8wk_Return']  = df['Price_Close'].pct_change(8).shift(-8)
    df['Fwd_12wk_Return'] = df['Price_Close'].pct_change(12).shift(-12)
    
    actors = {
        'Dealer':        'Dealer Net',
        'Asset Manager': 'Asset Manager Net',
        'Lev Money':     'Levered Net',
    }
    
    fwd_cols = ['Fwd_4wk_Return', 'Fwd_8wk_Return', 'Fwd_12wk_Return']
    
    for name, col in actors.items():
        print(f"\n{name}")
        print(f"  {'Horizon':<16} {'Corr':>8} {'PValue':>10} {'Sig':>6}")
        print(f"  {'-'*42}")
        for fwd_col in fwd_cols:
            aligned = df[[col, fwd_col]].dropna()
            corr, pvalue = stats.pearsonr(aligned[col], aligned[fwd_col])
            sig = '✓' if pvalue < 0.05 else ''
            print(f"  {fwd_col:<16} {corr:>8.3f} {pvalue:>10.4f} {sig:>6}")
    
    print()

In [385]:
def _print_crowding_regimes(df):
    
    print("=" * 50)
    print("SECTION 5 — CROWDING REGIME ANALYSIS")
    print("=" * 50)
    
    df = df.copy()
    df['Fwd_4wk_Return']  = df['Price_Close'].pct_change(4).shift(-4)
    df['Fwd_8wk_Return']  = df['Price_Close'].pct_change(8).shift(-8)
    df['Fwd_12wk_Return'] = df['Price_Close'].pct_change(12).shift(-12)
    
    crowding_cols = {
        'Lev Money Long':    'Levered Long Proportion',
        'Lev Money Short':   'Levered Short Proportion',
        'Asset Mgr Long':    'Asset Manager Long Proportion',
        'Dealer Long':       'Dealer Long Proportion',
    }
    
    fwd_cols = ['Fwd_4wk_Return', 'Fwd_8wk_Return', 'Fwd_12wk_Return']
    
    for crowd_name, crowd_col in crowding_cols.items():
        print(f"\n{crowd_name} Crowding Regimes")
        print(f"  {'Regime':<20} {'4wk Ret':>10} {'8wk Ret':>10} {'12wk Ret':>10} {'N':>6}")
        print(f"  {'-'*58}")
        
        df['Pctile'] = df[crowd_col].rank(pct=True)
        
        regimes = {
            'High  (top 20%)':    df['Pctile'] > 0.8,
            'Normal (mid 60%)':   df['Pctile'].between(0.2, 0.8),
            'Low (bottom 20%)':   df['Pctile'] < 0.2,
        }
        
        for regime_name, mask in regimes.items():
            subset = df[mask]
            r4  = subset['Fwd_4wk_Return'].mean()
            r8  = subset['Fwd_8wk_Return'].mean()
            r12 = subset['Fwd_12wk_Return'].mean()
            n   = len(subset)
            print(f"  {regime_name:<20} {r4:>10.4f} {r8:>10.4f} {r12:>10.4f} {n:>6}")
    
    from scipy import stats

    df['Fwd_4wk_Return']    = df['Price_Close'].pct_change(4).shift(-4)
    df['Dealer_Long_Pctile'] = df['Dealer Long Proportion'].rank(pct=True)

    high = df[df['Dealer_Long_Pctile'] > 0.8]['Fwd_4wk_Return'].dropna()
    low  = df[df['Dealer_Long_Pctile'] < 0.2]['Fwd_4wk_Return'].dropna()

    stat, pvalue = stats.ttest_ind(high, low)
    print(f"\nHigh vs Low Dealer Long — t-stat: {stat:.3f}, p-value: {pvalue:.4f}")

    # OI Spike Split
    oi_mean = df['Open_Interest_All'].mean()
    oi_std  = df['Open_Interest_All'].std()

    low_bucket = df[df['Dealer_Long_Pctile'] < 0.2].copy()
    low_bucket['Period'] = low_bucket.index.map(
        lambda i: 'Spike' if df.loc[i, 'Open_Interest_All'] > oi_mean + 2 * oi_std else 'Normal'
    )
    print("\n--- Low Dealer Long Bucket — OI Spike vs Normal ---")
    print(low_bucket.groupby('Period')['Fwd_4wk_Return'].agg(['mean', 'count']))
    print()
    print()

In [472]:
def _plot_three_panels(df):
    
    fig = make_subplots(
        rows=3, cols=1,
        shared_xaxes=True,
        vertical_spacing=0.05,
        subplot_titles=(
            'Price & Open Interest',
            'Actor Net Positions',
            'Crowding (% of OI)'
        ),
        specs=[[{"secondary_y": True}],
               [{"secondary_y": False}],
               [{"secondary_y": False}]]
    )

    # --- Panel 1: Price + OI ---
    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Price_Close'],
        name='Price',
        line=dict(color='white', width=2)
    ), row=1, col=1, secondary_y=False)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Open_Interest_All'],
        name='Open Interest',
        line=dict(color='rgba(255,255,0,0.5)', width=1, dash='dot'),
    ), row=1, col=1, secondary_y=True)

    # --- Panel 2: Actor Net Positions ---
    fig.add_hline(y=0, line_dash='dash', line_color='rgba(255,255,255,0.15)', row=2, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Dealer Net'],
        name='Dealer Net',
        line=dict(color='#ff4444', width=1.5)
    ), row=2, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Asset Manager Net'],
        name='Asset Mgr Net',
        line=dict(color='#00ffcc', width=1.5)
    ), row=2, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Levered Net'],
        name='Lev Money Net',
        line=dict(color='#ffaa00', width=1.5)
    ), row=2, col=1)

    # --- Panel 3: Crowding ---
    fig.add_hline(y=0, line_dash='dash', line_color='rgba(255,255,255,0.15)', row=3, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Levered Long Proportion'],
        name='Lev Long',
        line=dict(color='#ffaa00', width=1.5)
    ), row=3, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Levered Short Proportion'],
        name='Lev Short',
        line=dict(color='#ff4444', width=1.5)
    ), row=3, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Dealer Long Proportion'],
        name='Dealer Long',
        line=dict(color='#aa44ff', width=1.5)
    ), row=3, col=1)

    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Asset Manager Long Proportion'],
        name='Asset Mgr Long',
        line=dict(color='#00ffcc', width=1.5)
    ), row=3, col=1)

    # --- Layout ---
    instrument = df['Instrument'].iloc[0]
    start      = df['Report_Date_as_MM_DD_YYYY'].min().date()
    end        = df['Report_Date_as_MM_DD_YYYY'].max().date()

    fig.update_layout(
        template='plotly_dark',
        height=900,
        title=dict(
            text=f'COT Three Actor Analysis — {instrument} | {start} → {end}',
            font=dict(size=14, family='monospace', color='white')
        ),
        hovermode='x unified',
        legend=dict(orientation='h', y=-0.05),
        paper_bgcolor='#0a0a0a',
        plot_bgcolor='#0a0a0a',
    )

    fig.update_yaxes(title_text='Price',         row=1, col=1, secondary_y=False)
    fig.update_yaxes(title_text='Open Interest', row=1, col=1, secondary_y=True)
    fig.update_yaxes(title_text='Net Contracts', row=2, col=1)
    fig.update_yaxes(title_text='% of OI',       row=3, col=1)
    fig.update_xaxes(showgrid=True, gridcolor='rgba(255,255,255,0.05)')
    fig.update_yaxes(showgrid=True, gridcolor='rgba(255,255,255,0.05)')

    fig.show()

In [466]:
def run_cot_diagnostics(df_cot, instrument, start_date, end_date):
    
    df = process_COT(df_cot, instrument, start_date, end_date)  # what you have now
    
    _print_data_quality(df)        # Section 1
    _print_descriptives(df)        # Section 2
    _print_correlations(df)        # Section 3
    _print_forward_returns(df)     # Section 4
    
    _print_crowding_regimes(df)    # Section 5
    _plot_three_panels(df)         # Section 6
    
    
    return df

# Robustness Checks

In [411]:
def _test_lag_structure(df):
    
    print("\n" + "=" * 60)
    print("TEST 1 — LAG STRUCTURE")
    print("Does positioning CHANGE lead or lag price CHANGE?")
    print("=" * 60)
    
    df = df.copy()
    df['Price_Change'] = df['Price_Close'].diff()
    
    actors = {
        'Dealer':       'Dealer Net',
        'Asset Manager':'Asset Manager Net',
        'Lev Money':    'Levered Net',
    }
    
    for name, col in actors.items():
        df['Actor_Change'] = df[col].diff()
        print(f"\n{name}")
        print(f"  {'Lag':<6} {'Corr':>8} {'PValue':>10} {'Sig':>6}  Direction")
        print(f"  {'-'*50}")
        for lag in range(-4, 5):
            aligned = pd.DataFrame({
                'actor': df['Actor_Change'].shift(lag),
                'price': df['Price_Change']
            }).dropna()
            corr, pvalue = stats.pearsonr(aligned['actor'], aligned['price'])
            sig    = '✓' if pvalue < 0.05 else ''
            if lag < 0:
                direction = f'price leads actor by {abs(lag)}wk'
            elif lag == 0:
                direction = 'concurrent'
            else:
                direction = f'actor leads price by {lag}wk'
            print(f"  {lag:<6} {corr:>8.3f} {pvalue:>10.4f} {sig:>6}  {direction}")

In [427]:
def _test_asymmetry(df):
    
    print("\n" + "=" * 60)
    print("TEST 2 — ASYMMETRY")
    print("Do signals work differently in up vs down weeks?")
    print("=" * 60)
    
    df = df.copy()
    df['Price_Change'] = df['Price_Close'].diff()
    df['Actor_Change_Dealer']  = df['Dealer Net'].diff()
    df['Actor_Change_AssetMgr']= df['Asset Manager Net'].diff()
    df['Actor_Change_Lev']     = df['Levered Net'].diff()
    
    up_weeks   = df[df['Price_Change'] > 0].copy()
    down_weeks = df[df['Price_Change'] < 0].copy()
    
    actors = {
        'Dealer':        'Actor_Change_Dealer',
        'Asset Manager': 'Actor_Change_AssetMgr',
        'Lev Money':     'Actor_Change_Lev',
    }
    
    print(f"\n  {'Actor':<20} {'Up Corr':>10} {'Up Sig':>8} {'Down Corr':>10} {'Down Sig':>10} {'Asymmetry':>10}")
    print(f"  {'-'*72}")
    
    for name, col in actors.items():
        # Up weeks
        up_aligned = pd.DataFrame({
            'actor': up_weeks[col],
            'price': up_weeks['Price_Change']
        }).dropna()
        up_corr, up_p = stats.pearsonr(up_aligned['actor'], up_aligned['price'])
        
        # Down weeks
        dn_aligned = pd.DataFrame({
            'actor': down_weeks[col],
            'price': down_weeks['Price_Change']
        }).dropna()
        dn_corr, dn_p = stats.pearsonr(dn_aligned['actor'], dn_aligned['price'])
        
        up_sig = '✓' if up_p < 0.05 else ''
        dn_sig = '✓' if dn_p < 0.05 else ''
        asymmetry = round(abs(up_corr) - abs(dn_corr), 3)
        
        print(f"  {name:<20} {up_corr:>10.3f} {up_sig:>8} {dn_corr:>10.3f} {dn_sig:>10} {asymmetry:>10.3f}")
    
    print(f"\n  N up weeks  : {len(up_weeks)}")
    print(f"  N down weeks: {len(down_weeks)}")
    print()

In [429]:
def _test_outlier_sensitivity(df):
    
    print("\n" + "=" * 60)
    print("TEST 3 — OUTLIER SENSITIVITY")
    print("Do results survive winsorisation of extreme values?")
    print("=" * 60)
    
    from scipy.stats import mstats
    
    df = df.copy()
    df['Price_Change'] = df['Price_Close'].diff()
    
    actors = {
        'Dealer':        'Dealer Net',
        'Asset Manager': 'Asset Manager Net',
        'Lev Money':     'Levered Net',
    }
    
    print(f"\n  {'Actor':<20} {'Raw Corr':>10} {'Wins 5%':>10} {'Wins 10%':>10} {'Stable?':>10}")
    print(f"  {'-'*64}")
    
    for name, col in actors.items():
        df['Actor_Change'] = df[col].diff()
        
        aligned = pd.DataFrame({
            'actor': df['Actor_Change'],
            'price': df['Price_Change']
        }).dropna()
        
        raw_corr, _  = stats.pearsonr(aligned['actor'], aligned['price'])
        
        # Winsorise at 5%
        wins_5       = mstats.winsorize(aligned['actor'], limits=[0.05, 0.05])
        corr_5, _    = stats.pearsonr(wins_5, aligned['price'])
        
        # Winsorise at 10%
        wins_10      = mstats.winsorize(aligned['actor'], limits=[0.10, 0.10])
        corr_10, _   = stats.pearsonr(wins_10, aligned['price'])
        
        # Stable if correlation doesn't change by more than 0.05
        stable = '✓' if abs(raw_corr - corr_10) < 0.05 else '✗'
        
        print(f"  {name:<20} {raw_corr:>10.3f} {corr_5:>10.3f} {corr_10:>10.3f} {stable:>10}")
    
    print()

In [432]:
def _test_nonlinear(df):
    
    print("\n" + "=" * 60)
    print("TEST 4 — NON-LINEAR RELATIONSHIPS")
    print("Spearman vs Pearson — is the relationship non-linear?")
    print("=" * 60)
    
    from scipy.stats import spearmanr
    
    df = df.copy()
    df['Price_Change'] = df['Price_Close'].diff()
    
    actors = {
        'Dealer':        'Dealer Net',
        'Asset Manager': 'Asset Manager Net',
        'Lev Money':     'Levered Net',
    }
    
    print(f"\n  {'Actor':<20} {'Pearson':>10} {'Spearman':>10} {'Difference':>12} {'Non-linear?':>12}")
    print(f"  {'-'*68}")
    
    for name, col in actors.items():
        df['Actor_Change'] = df[col].diff()
        
        aligned = pd.DataFrame({
            'actor': df['Actor_Change'],
            'price': df['Price_Change']
        }).dropna()
        
        pearson_r,  _  = stats.pearsonr(aligned['actor'],  aligned['price'])
        spearman_r, _  = spearmanr(aligned['actor'], aligned['price'])
        
        diff       = abs(spearman_r) - abs(pearson_r)
        nonlinear  = '✓' if abs(diff) > 0.05 else '✗'
        
        print(f"  {name:<20} {pearson_r:>10.3f} {spearman_r:>10.3f} {diff:>12.3f} {nonlinear:>12}")
    
    print()

In [ ]:
def _plot_rolling_correlations(df):
    
    print("\n" + "=" * 60)
    print("TEST 5 — ROLLING CORRELATIONS VS PRICE LEVELS")
    print("=" * 60)
    
    df_roll = df.set_index('Report_Date_as_MM_DD_YYYY').copy()
    
    actors = {
        'Dealer Net':        '#ff4444',
        'Asset Manager Net': '#00ffcc',
        'Levered Net':       '#ffaa00',
    }
    
    rolling_corrs = pd.DataFrame()
    for actor, color in actors.items():
        rolling_corrs[actor] = df_roll[actor].rolling(52).corr(df_roll['Price_Close'])
    
    fig = go.Figure()
    
    for actor, color in actors.items():
        fig.add_trace(go.Scatter(
            x=rolling_corrs.index,
            y=rolling_corrs[actor],
            name=actor,
            line=dict(color=color, width=1.5)
        ))
    
    fig.add_hline(y=0,    line_dash='dash', line_color='rgba(255,255,255,0.3)')
    fig.add_hline(y=0.5,  line_dash='dot',  line_color='rgba(255,255,255,0.15)')
    fig.add_hline(y=-0.5, line_dash='dot',  line_color='rgba(255,255,255,0.15)')
    
    fig.update_layout(
        template='plotly_dark',
        title='Rolling 52-Week Correlation vs Price Levels',
        height=450,
        hovermode='x unified',
        paper_bgcolor='#0a0a0a',
        yaxis_title='Correlation',
    )
    
    fig.show()

In [438]:

def _plot_rolling_correlations_diff(df):
    
    print("\n" + "=" * 60)
    print("TEST 6 — ROLLING CORRELATIONS VS PRICE CHANGES")
    print("=" * 60)
    
    df_roll = df.set_index('Report_Date_as_MM_DD_YYYY').copy()
    df_diff = df_roll[['Dealer Net', 'Asset Manager Net', 'Levered Net', 'Price_Close']].diff()
    
    actors = {
        'Dealer Net':        '#ff4444',
        'Asset Manager Net': '#00ffcc',
        'Levered Net':       '#ffaa00',
    }
    
    rolling_corrs_diff = pd.DataFrame()
    for actor in actors:
        rolling_corrs_diff[actor] = df_diff[actor].rolling(52).corr(df_diff['Price_Close'])
    
    fig = go.Figure()
    
    for actor, color in actors.items():
        fig.add_trace(go.Scatter(
            x=rolling_corrs_diff.index,
            y=rolling_corrs_diff[actor],
            name=actor,
            line=dict(color=color, width=1.5)
        ))
    
    fig.add_hline(y=0,    line_dash='dash', line_color='rgba(255,255,255,0.3)')
    fig.add_hline(y=0.5,  line_dash='dot',  line_color='rgba(255,255,255,0.15)')
    fig.add_hline(y=-0.5, line_dash='dot',  line_color='rgba(255,255,255,0.15)')
    
    fig.update_layout(
        template='plotly_dark',
        title='Rolling 52-Week Correlation vs Price Changes (First Differenced)',
        height=450,
        hovermode='x unified',
        paper_bgcolor='#0a0a0a',
        yaxis_title='Correlation',
    )
    
    fig.show()

In [443]:
def _test_long_short_decomposition(df):
    
    print("\n" + "=" * 60)
    print("TEST 7 — LONG VS SHORT DECOMPOSITION")
    print("Is the regime break from adding shorts or reducing longs?")
    print("=" * 60)
    
    df = df.copy()
    df_roll = df.set_index('Report_Date_as_MM_DD_YYYY')
    df_diff = df_roll[[
        'Lev_Money_Positions_Long_All',
        'Lev_Money_Positions_Short_All',
        'Asset_Mgr_Positions_Long_All',
        'Asset_Mgr_Positions_Short_All',
        'Dealer_Positions_Long_All',
        'Dealer_Positions_Short_All',
        'Price_Close'
    ]].diff()
    
    components = {
        'Lev Money Long':    'Lev_Money_Positions_Long_All',
        'Lev Money Short':   'Lev_Money_Positions_Short_All',
        'Asset Mgr Long':    'Asset_Mgr_Positions_Long_All',
        'Asset Mgr Short':   'Asset_Mgr_Positions_Short_All',
        'Dealer Long':       'Dealer_Positions_Long_All',
        'Dealer Short':      'Dealer_Positions_Short_All',
    }
    
    # Rolling correlations
    rolling = pd.DataFrame(index=df_roll.index)
    for name, col in components.items():
        rolling[name] = df_diff[col].rolling(52).corr(df_diff['Price_Close'])
    
    # Print current (last row) correlations
    print(f"\n  {'Component':<25} {'Current Corr':>14} {'2010-2018 Mean':>16} {'2019-2025 Mean':>16}")
    print(f"  {'-'*73}")
    
    pre  = rolling[df_roll.index < '2019-01-01']
    post = rolling[df_roll.index >= '2019-01-01']
    
    for name in components:
        current   = rolling[name].iloc[-1]
        pre_mean  = pre[name].mean()
        post_mean = post[name].mean()
        print(f"  {name:<25} {current:>14.3f} {pre_mean:>16.3f} {post_mean:>16.3f}")
    
    # Plot
    lev_components = ['Lev Money Long', 'Lev Money Short']
    colors = {'Lev Money Long': '#ffaa00', 'Lev Money Short': '#ff4444'}
    
    fig = go.Figure()
    for comp in lev_components:
        fig.add_trace(go.Scatter(
            x=rolling.index,
            y=rolling[comp],
            name=comp,
            line=dict(color=colors[comp], width=1.5)
        ))
    
    fig.add_hline(y=0, line_dash='dash', line_color='rgba(255,255,255,0.3)')
    
    fig.update_layout(
        template='plotly_dark',
        title='Rolling 52-Week Correlation — Lev Money Long vs Short vs Price Changes',
        height=400,
        hovermode='x unified',
        paper_bgcolor='#0a0a0a',
        yaxis_title='Correlation',
    )
    
    fig.show()
    print()

In [450]:
def _test_oi_composition(df):
    
    print("\n" + "=" * 60)
    print("TEST 8 — OI COMPOSITION OVER TIME")
    print("How has each actor's market share shifted?")
    print("=" * 60)
    
    df = df.copy()
    df_roll = df.set_index('Report_Date_as_MM_DD_YYYY')
    
    # Compute each actor's total participation as % of OI
    df_roll['Lev_Total']     = (df_roll['Lev_Money_Positions_Long_All']  + df_roll['Lev_Money_Positions_Short_All'])  / df_roll['Open_Interest_All']
    df_roll['AssetMgr_Total']= (df_roll['Asset_Mgr_Positions_Long_All']  + df_roll['Asset_Mgr_Positions_Short_All'])  / df_roll['Open_Interest_All']
    df_roll['Dealer_Total']  = (df_roll['Dealer_Positions_Long_All']     + df_roll['Dealer_Positions_Short_All'])     / df_roll['Open_Interest_All']
    
    # Rolling 52-week mean of each
    rolling_share = pd.DataFrame()
    rolling_share['Lev Money']     = df_roll['Lev_Total'].rolling(52).mean()
    rolling_share['Asset Manager'] = df_roll['AssetMgr_Total'].rolling(52).mean()
    rolling_share['Dealer']        = df_roll['Dealer_Total'].rolling(52).mean()
    
    # Print summary
    print(f"\n  {'Actor':<20} {'2010-2018 Mean':>16} {'2019-2025 Mean':>16} {'Current':>10}")
    print(f"  {'-'*64}")
    
    pre  = rolling_share[df_roll.index < '2019-01-01']
    post = rolling_share[df_roll.index >= '2019-01-01']
    
    for actor in ['Lev Money', 'Asset Manager', 'Dealer']:
        pre_mean  = pre[actor].mean()
        post_mean = post[actor].mean()
        current   = rolling_share[actor].iloc[-1]
        print(f"  {actor:<20} {pre_mean:>16.1%} {post_mean:>16.1%} {current:>10.1%}")
    
    # Plot
    colors = {
    'Lev Money':     dict(line='#ffaa00', fill='rgba(255,170,0,0.08)'),
    'Asset Manager': dict(line='#00ffcc', fill='rgba(0,255,204,0.08)'),
    'Dealer':        dict(line='#ff4444', fill='rgba(255,68,68,0.08)'),
    }

    fig = go.Figure()
    for actor, color in colors.items():
        fig.add_trace(go.Scatter(
            x=rolling_share.index,
            y=rolling_share[actor],
            name=actor,
            line=dict(color=color['line'], width=1.5),
            fill='tozeroy',
            fillcolor=color['fill']
        ))
    
    fig.show()
    print()

In [462]:
def _composite_signal_backtest(df):
    
    print("\n" + "=" * 60)
    print("TEST 9 — COMPOSITE SIGNAL BACKTEST")
    print("Regime filter — accumulation vs distribution phase")
    print("=" * 60)
    
    df = df.copy()
    df = df[df['Report_Date_as_MM_DD_YYYY'] >= '2019-01-01'].copy()
    
    # --- Original tercile test (keep for reference) ---
    df['AssetMgr_Change'] = df['Asset Manager Net'].diff()
    df['LevMoney_Change']  = df['Levered Net'].diff()
    df['AssetMgr_Rank']   = df['AssetMgr_Change'].rolling(52).rank(pct=True)
    df['LevMoney_Rank']    = df['LevMoney_Change'].rolling(52).rank(pct=True)
    df['Composite']        = (df['AssetMgr_Rank'] + (1 - df['LevMoney_Rank'])) / 2
    df = df.dropna(subset=['Composite'])
    df['Fwd_4wk']  = df['Price_Close'].pct_change(4).shift(-4)
    df['Fwd_8wk']  = df['Price_Close'].pct_change(8).shift(-8)
    df['Fwd_12wk'] = df['Price_Close'].pct_change(12).shift(-12)
    df['Signal_Tercile'] = pd.qcut(df['Composite'], q=3, labels=['Low', 'Mid', 'High'])
    
    print(f"\n--- Weekly Signal Terciles (for reference) ---")
    print(f"  {'Tercile':<10} {'4wk Ret':>10} {'8wk Ret':>10} {'12wk Ret':>10} {'N':>6}")
    print(f"  {'-'*50}")
    for tercile in ['Low', 'Mid', 'High']:
        subset = df[df['Signal_Tercile'] == tercile]
        print(f"  {tercile:<10} {subset['Fwd_4wk'].mean():>10.4f} {subset['Fwd_8wk'].mean():>10.4f} {subset['Fwd_12wk'].mean():>10.4f} {len(subset):>6}")
    high = df[df['Signal_Tercile'] == 'High']['Fwd_4wk'].dropna()
    low  = df[df['Signal_Tercile'] == 'Low']['Fwd_4wk'].dropna()
    stat, pvalue = stats.ttest_ind(high, low)
    print(f"\n  High vs Low — t-stat: {stat:.3f}, p-value: {pvalue:.4f}")

    # --- Regime Filter ---
    print(f"\n--- Regime Filter (12-week rolling positioning) ---")
    
    df['AssetMgr_Regime'] = df['Asset Manager Net'].rolling(12).mean().rank(pct=True)
    df['LevMoney_Regime']  = df['Levered Net'].rolling(12).mean().rank(pct=True)
    
    # Simple average of both regime ranks
    df['Combined_Regime'] = (df['AssetMgr_Regime'] + (1 - df['LevMoney_Regime'])) / 2

    df['Regime'] = 'Neutral'
    df.loc[df['Combined_Regime'] > 0.65, 'Regime'] = 'Bullish'
    df.loc[df['Combined_Regime'] < 0.35, 'Regime'] = 'Bearish'
    
    print(f"\n  {'Regime':<10} {'4wk Ret':>10} {'8wk Ret':>10} {'12wk Ret':>10} {'N':>6}")
    print(f"  {'-'*50}")
    for regime in ['Bullish', 'Neutral', 'Bearish']:
        subset = df[df['Regime'] == regime]
        r4  = subset['Fwd_4wk'].mean()
        r8  = subset['Fwd_8wk'].mean()
        r12 = subset['Fwd_12wk'].mean()
        n   = len(subset)
        print(f"  {regime:<10} {r4:>10.4f} {r8:>10.4f} {r12:>10.4f} {n:>6}")
    
    bull = df[df['Regime'] == 'Bullish']['Fwd_4wk'].dropna()
    bear = df[df['Regime'] == 'Bearish']['Fwd_4wk'].dropna()
    if len(bull) > 1 and len(bear) > 1:
        stat, pvalue = stats.ttest_ind(bull, bear)
        print(f"\n  Bullish vs Bearish — t-stat: {stat:.3f}, p-value: {pvalue:.4f}")
    
    # Regime distribution
    print(f"\n  Regime Distribution:")
    print(df['Regime'].value_counts().to_string())
    
    # Plot regime over price
    regime_colors = {'Bullish': 'rgba(0,255,100,0.15)', 
                     'Bearish': 'rgba(255,50,50,0.15)', 
                     'Neutral': 'rgba(150,150,150,0.05)'}
    
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.05,
                        subplot_titles=('S&P 500 Price with Regime', 
                                        'Actor Positioning Regimes'))
    
    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['Price_Close'],
        name='Price',
        line=dict(color='white', width=2)
    ), row=1, col=1)
    
    # Shade regimes on price panel
    for _, row_data in df.iterrows():
        if row_data['Regime'] != 'Neutral':
            fig.add_vrect(
                x0=row_data['Report_Date_as_MM_DD_YYYY'],
                x1=row_data['Report_Date_as_MM_DD_YYYY'] + pd.Timedelta(days=7),
                fillcolor=regime_colors[row_data['Regime']],
                layer='below', line_width=0,
                row=1, col=1
            )
    
    # Plot regime ranks
    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['AssetMgr_Regime'],
        name='Asset Mgr Regime',
        line=dict(color='#00ffcc', width=1.5)
    ), row=2, col=1)
    
    fig.add_trace(go.Scatter(
        x=df['Report_Date_as_MM_DD_YYYY'],
        y=df['LevMoney_Regime'],
        name='Lev Money Regime',
        line=dict(color='#ffaa00', width=1.5)
    ), row=2, col=1)
    
    fig.add_hline(y=0.6, line_dash='dot', line_color='rgba(0,255,100,0.4)', row=2, col=1)
    fig.add_hline(y=0.4, line_dash='dot', line_color='rgba(255,50,50,0.4)',  row=2, col=1)
    
    fig.update_layout(
        template='plotly_dark',
        title='COT Regime Filter — Bullish/Bearish/Neutral 2019-2025',
        height=650,
        hovermode='x unified',
        paper_bgcolor='#0a0a0a',
    )
    
    fig.show()
    print()

In [460]:
def run_robustness_tests(df):
    
    print("=" * 60)
    print("ROBUSTNESS & INVESTIGATIVE ANALYSIS")
    print(f"Instrument : {df['Instrument'].iloc[0]}")
    print(f"Period     : {df['Report_Date_as_MM_DD_YYYY'].min().date()} → {df['Report_Date_as_MM_DD_YYYY'].max().date()}")
    print("=" * 60)
    
    #_test_lag_structure(df)
    #_test_asymmetry(df)
    #_test_outlier_sensitivity(df)
    #_test_nonlinear(df)
    #_plot_rolling_correlations(df)
    #_plot_rolling_correlations_diff(df)
    #_test_long_short_decomposition(df)
    #_test_oi_composition(df)
    _composite_signal_backtest(df)

# Runs

### Pre Checks

In [ ]:
df_raw = download_cot_data(
    years=list(range(2010, 2026)),
    report_type='combined'
)

Fetching combined COT 2010 from https://www.cftc.gov/files/dea/history/com_fin_xls_2010.zip...
  ✓ 2010 fetched successfully
Fetching combined COT 2011 from https://www.cftc.gov/files/dea/history/com_fin_xls_2011.zip...
  ✓ 2011 fetched successfully
Fetching combined COT 2012 from https://www.cftc.gov/files/dea/history/com_fin_xls_2012.zip...
  ✓ 2012 fetched successfully
Fetching combined COT 2013 from https://www.cftc.gov/files/dea/history/com_fin_xls_2013.zip...
  ✓ 2013 fetched successfully
Fetching combined COT 2014 from https://www.cftc.gov/files/dea/history/com_fin_xls_2014.zip...
  ✓ 2014 fetched successfully
Fetching combined COT 2015 from https://www.cftc.gov/files/dea/history/com_fin_xls_2015.zip...
  ✓ 2015 fetched successfully
Fetching combined COT 2016 from https://www.cftc.gov/files/dea/history/com_fin_xls_2016.zip...
  ✓ 2016 fetched successfully
Fetching combined COT 2017 from https://www.cftc.gov/files/dea/history/com_fin_xls_2017.zip...
  ✓ 2017 fetched successfully
Fetching combined COT 2018 from https://www.cftc.gov/files/dea/history/com_fin_xls_2018.zip...
  ✓ 2018 fetched successfully
Fetching combined COT 2019 from https://www.cftc.gov/files/dea/history/com_fin_xls_2019.zip...
  ✓ 2019 fetched successfully
Fetching combined COT 2020 from https://www.cftc.gov/files/dea/history/com_fin_xls_2020.zip...
  ✓ 2020 fetched successfully
Fetching combined COT 2021 from https://www.cftc.gov/files/dea/history/com_fin_xls_2021.zip...
  ✓ 2021 fetched successfully
Fetching combined COT 2022 from https://www.cftc.gov/files/dea/history/com_fin_xls_2022.zip...
  ✓ 2022 fetched successfully
Fetching combined COT 2023 from https://www.cftc.gov/files/dea/history/com_fin_xls_2023.zip...
  ✓ 2023 fetched successfully
Fetching combined COT 2024 from https://www.cftc.gov/files/dea/history/com_fin_xls_2024.zip...
  ✓ 2024 fetched successfully
Fetching combined COT 2025 from https://www.cftc.gov/files/dea/history/com_fin_xls_2025.zip...
  ✓ 2025 fetched successfully

NameError: name 'clean_cot_data' is not defined

In [399]:
get_dominant_contracts(df_raw, 'S&P 500')

Variants: For S&P 500:
ADJUSTED INT RATE S&P 500 TOTL - CHICAGO MERCANTILE EXCHANGE
E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE
E-MINI S&P 500 STOCK INDEX - CHICAGO MERCANTILE EXCHANGE
MICRO E-MINI S&P 500 INDEX - CHICAGO MERCANTILE EXCHANGE
S&P 500 ANNUAL DIVIDEND INDEX - CHICAGO MERCANTILE EXCHANGE
S&P 500 Consolidated - CHICAGO MERCANTILE EXCHANGE
S&P 500 QUARTERLY DIVIDEND IND - CHICAGO MERCANTILE EXCHANGE
S&P 500 STOCK INDEX - CHICAGO MERCANTILE EXCHANGE
S&P 500 TOTAL RETURN INDEX - CHICAGO MERCANTILE EXCHANGE

In [400]:
cot_clean = clean_financial_cot_data(df_raw, INSTRUMENT_MAP)
cot_clean

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/588470530.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Instrument,Report_Date_as_MM_DD_YYYY,Open_Interest_All,Dealer_Positions_Long_All,Dealer_Positions_Short_All,Asset_Mgr_Positions_Long_All,Asset_Mgr_Positions_Short_All,Lev_Money_Positions_Long_All,Lev_Money_Positions_Short_All
0,SP500,2010-07-20,3950120,279468,755194,1844743,783283,467012,1088994
1,SP500,2010-07-27,3940657,293075,787898,1821705,765662,435021,1043743
2,SP500,2010-08-03,3911845,292831,814138,1779407,738042,412338,1015510
3,SP500,2010-08-10,3942957,300815,857555,1818350,734506,406577,993971
4,SP500,2010-08-17,4031779,325472,795652,1785410,820317,500594,1012640
...,...,...,...,...,...,...,...,...,...
802,SP500,2025-12-02,5605697,302036,1591872,2311344,432475,357320,1242633
803,SP500,2025-12-09,5740777,311644,1617103,2334410,419409,334427,1232507
804,SP500,2025-12-16,6380535,330625,1761295,2334087,407375,408269,1189896
805,SP500,2025-12-23,4910939,260369,1667888,2302717,431969,327160,1071391
806,SP500,2025-12-30,4979545,254605,1675757,2338125,454652,289037,1018138

# Graphs

### Full

In [481]:
print('Full history')
run_cot_diagnostics(cot_clean, 'SP500', '2010-01-01', '2025-12-31')
print('Diagnostics END_________________________________________________________________________________')

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/2219192598.py:35: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Full history
==================================================
SECTION 1 — DATA QUALITY
==================================================

Rows       : 798
Date Range : 2010-07-20 → 2025-12-30

Expected Weeks : 807
Missing Weeks  : 9
Missing Dates  : [datetime.date(2012, 10, 30), datetime.date(2012, 12, 25), datetime.date(2013, 1, 1), datetime.date(2017, 7, 4), datetime.date(2018, 12, 25), datetime.date(2019, 1, 1), datetime.date(2020, 12, 22), datetime.date(2023, 7, 4), datetime.date(2025, 11, 11)]

Nulls : None ✓

OI Spikes (>2 std devs) : 41
Report_Date_as_MM_DD_YYYY  Open_Interest_All
               2020-03-17            8622736
               2023-05-02            6526923
               2023-05-09            6607327
               2023-05-16            6668927
               2023-05-23            6749811
               2023-05-30            6945040
               2023-06-06            7055301
               2023-06-13            8170247
               2023-07-18            6707667
               2023-08-29            6486374
               2023-09-12            6966110
               2023-09-26            6496171
               2023-10-03            6550685
               2023-10-24            6474351
               2023-10-31            6503266
               2023-11-07            6523739
               2023-11-14            6875964
               2023-11-21            6853709
               2023-11-28            6893768
               2023-12-05            6974635
               2023-12-12            7931741
               2024-01-30            6689456
               2024-02-06            6643489
               2024-02-13            6933764
               2024-02-20            6728892
               2024-02-27            7160472
               2024-03-05            7192032
               2024-03-12            8193256
               2024-04-16            6468666
               2024-06-11            6623813
               2024-06-18            7598493
               2024-08-06            6771465
               2024-09-17            7324339
               2024-11-12            6560325
               2024-12-10            6566543
               2024-12-17            7141865
               2025-03-11            6704628
               2025-03-18            6989524
               2025-04-08            7749237
               2025-06-17            6689971
               2025-09-16            6667424

==================================================
SECTION 2 — DESCRIPTIVE STATISTICS
==================================================

--- Actor Net Positions ---

Dealer
  Mean :     -559,458
  Max  :      467,419
  Min  :   -1,886,960
  Std  :      461,474

Asset Manager
  Mean :      984,453
  Max  :    2,204,967
  Min  :      200,873
  Std  :      444,603

Lev Money
  Mean :     -390,907
  Max  :      103,287
  Min  :   -1,099,608
  Std  :      208,526

--- Average Crowding (% of OI) ---
  Dealer              : 26.4%
  Asset Manager       : 53.0%
  Lev Money           : 26.8%

--- Structural Net Check ---
  Total Net Mean :       34,087  (should be near zero)
  Total Net Std  :      192,744

==================================================
SECTION 3 — CORRELATIONS VS PRICE LEVELS
==================================================

Dealer
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.452     0.0000      ✓
  1        -0.448     0.0000      ✓
  2        -0.445     0.0000      ✓
  3        -0.441     0.0000      ✓
  4        -0.437     0.0000      ✓
  5        -0.435     0.0000      ✓
  6        -0.432     0.0000      ✓
  7        -0.429     0.0000      ✓
  8        -0.428     0.0000      ✓
  9        -0.426     0.0000      ✓
  10       -0.425     0.0000      ✓
  11       -0.423     0.0000      ✓
  12       -0.421     0.0000      ✓

Asset Manager
  Lag        Corr     PValue    Sig
  ----------------------------------
  0         0.564     0.0000      ✓
  1         0.560     0.0000      ✓
  2         0.557     0.0000      ✓
  3         0.554     0.0000      ✓
  4         0.551     0.0000      ✓
  5         0.547     0.0000      ✓
  6         0.544     0.0000      ✓
  7         0.542     0.0000      ✓
  8         0.539     0.0000      ✓
  9         0.537     0.0000      ✓
  10        0.534     0.0000      ✓
  11        0.531     0.0000      ✓
  12        0.528     0.0000      ✓

Lev Money
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.300     0.0000      ✓
  1        -0.297     0.0000      ✓
  2        -0.294     0.0000      ✓
  3        -0.290     0.0000      ✓
  4        -0.285     0.0000      ✓
  5        -0.279     0.0000      ✓
  6        -0.276     0.0000      ✓
  7        -0.272     0.0000      ✓
  8        -0.268     0.0000      ✓
  9        -0.263     0.0000      ✓
  10       -0.258     0.0000      ✓
  11       -0.254     0.0000      ✓
  12       -0.249     0.0000      ✓

==================================================
SECTION 4 — FORWARD RETURN ANALYSIS
==================================================

Dealer
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.033     0.3599
  Fwd_8wk_Return      0.018     0.6091
  Fwd_12wk_Return    -0.003     0.9278

Asset Manager
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.037     0.2969
  Fwd_8wk_Return     -0.041     0.2511
  Fwd_12wk_Return    -0.036     0.3156

Lev Money
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.022     0.5383
  Fwd_8wk_Return     -0.024     0.4967
  Fwd_12wk_Return    -0.035     0.3241

==================================================
SECTION 5 — CROWDING REGIME ANALYSIS
==================================================

Lev Money Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0113     0.0236     0.0357    160
  Normal (mid 60%)         0.0086     0.0175     0.0242    479
  Low (bottom 20%)         0.0130     0.0243     0.0418    159

Lev Money Short Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0067     0.0141     0.0208    160
  Normal (mid 60%)         0.0104     0.0199     0.0315    479
  Low (bottom 20%)         0.0122     0.0268     0.0349    159

Asset Mgr Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0051     0.0088     0.0126    160
  Normal (mid 60%)         0.0112     0.0219     0.0324    479
  Low (bottom 20%)         0.0113     0.0260     0.0398    159

Dealer Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0167     0.0312     0.0421    160
  Normal (mid 60%)         0.0096     0.0194     0.0269    479
  Low (bottom 20%)         0.0042     0.0108     0.0269    159

High vs Low Dealer Long — t-stat: 2.580, p-value: 0.0103

--- Low Dealer Long Bucket — OI Spike vs Normal ---
            mean  count
Period
Normal  0.003256    146
Spike   0.017347     11

Diagnostics END_________________________________________________________________________________

### 2018-01-01 -> 2022-12-31

In [482]:
print('Full history')
run_cot_diagnostics(cot_clean, 'SP500', '2018-01-01', '2022-12-31')
print('Diagnostics END_________________________________________________________________________________')

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/2219192598.py:35: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Full history
==================================================
SECTION 1 — DATA QUALITY
==================================================

Rows       : 258
Date Range : 2018-01-02 → 2022-12-27

Expected Weeks : 261
Missing Weeks  : 3
Missing Dates  : [datetime.date(2018, 12, 25), datetime.date(2019, 1, 1), datetime.date(2020, 12, 22)]

Nulls : None ✓

OI Spikes (>2 std devs) : 12
Report_Date_as_MM_DD_YYYY  Open_Interest_All
               2018-02-06            6043415
               2018-02-13            5746185
               2018-03-13            5727006
               2018-12-18            5620538
               2020-03-10            6378788
               2020-03-17            8622736
               2020-03-24            6178390
               2020-03-31            5947962
               2020-04-07            5903191
               2020-04-14            5901634
               2020-04-21            5671263
               2020-06-16            5662529

==================================================
SECTION 2 — DESCRIPTIVE STATISTICS
==================================================

--- Actor Net Positions ---

Dealer
  Mean :     -406,645
  Max  :      467,419
  Min  :   -1,048,136
  Std  :      332,112

Asset Manager
  Mean :      780,264
  Max  :    1,371,687
  Min  :      215,331
  Std  :      259,869

Lev Money
  Mean :     -227,646
  Max  :      103,287
  Min  :     -697,488
  Std  :      147,813

--- Average Crowding (% of OI) ---
  Dealer              : 25.0%
  Asset Manager       : 52.6%
  Lev Money           : 19.4%

--- Structural Net Check ---
  Total Net Mean :      145,972  (should be near zero)
  Total Net Std  :      172,182

==================================================
SECTION 3 — CORRELATIONS VS PRICE LEVELS
==================================================

Dealer
  Lag        Corr     PValue    Sig
  ----------------------------------
  0         0.155     0.0128      ✓
  1         0.158     0.0110      ✓
  2         0.163     0.0091      ✓
  3         0.166     0.0080      ✓
  4         0.169     0.0068      ✓
  5         0.172     0.0062      ✓
  6         0.172     0.0063      ✓
  7         0.171     0.0066      ✓
  8         0.170     0.0070      ✓
  9         0.171     0.0069      ✓
  10        0.169     0.0076      ✓
  11        0.166     0.0089      ✓
  12        0.163     0.0106      ✓

Asset Manager
  Lag        Corr     PValue    Sig
  ----------------------------------
  0         0.024     0.6985
  1         0.023     0.7114
  2         0.019     0.7672
  3         0.011     0.8599
  4         0.002     0.9742
  5        -0.005     0.9310
  6        -0.007     0.9091
  7        -0.005     0.9381
  8        -0.004     0.9462
  9        -0.002     0.9696
  10        0.004     0.9541
  11        0.010     0.8784
  12        0.018     0.7804

Lev Money
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.010     0.8790
  1        -0.005     0.9378
  2         0.000     0.9969
  3         0.012     0.8488
  4         0.023     0.7203
  5         0.037     0.5549
  6         0.045     0.4792
  7         0.049     0.4415
  8         0.052     0.4127
  9         0.049     0.4448
  10        0.046     0.4716
  11        0.042     0.5068
  12        0.041     0.5245

==================================================
SECTION 4 — FORWARD RETURN ANALYSIS
==================================================

Dealer
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.121     0.0545
  Fwd_8wk_Return      0.144     0.0224      ✓
  Fwd_12wk_Return     0.127     0.0475      ✓

Asset Manager
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.167     0.0075      ✓
  Fwd_8wk_Return     -0.212     0.0007      ✓
  Fwd_12wk_Return    -0.191     0.0026      ✓

Lev Money
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.056     0.3723
  Fwd_8wk_Return      0.055     0.3857
  Fwd_12wk_Return    -0.002     0.9714

==================================================
SECTION 5 — CROWDING REGIME ANALYSIS
==================================================

Lev Money Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0080     0.0122     0.0108     52
  Normal (mid 60%)         0.0056     0.0145     0.0226    155
  Low (bottom 20%)         0.0086     0.0132     0.0225     51

Lev Money Short Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0021     0.0025     0.0192     52
  Normal (mid 60%)         0.0053     0.0147     0.0171    155
  Low (bottom 20%)         0.0153     0.0213     0.0296     51

Asset Mgr Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0034    -0.0068    -0.0016     52
  Normal (mid 60%)         0.0095     0.0206     0.0233    155
  Low (bottom 20%)         0.0014     0.0145     0.0354     51

Dealer Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0187     0.0289     0.0420     52
  Normal (mid 60%)         0.0109     0.0227     0.0247    155
  Low (bottom 20%)        -0.0179    -0.0266    -0.0123     51

High vs Low Dealer Long — t-stat: 3.185, p-value: 0.0019

--- Low Dealer Long Bucket — OI Spike vs Normal ---
            mean  count
Period
Normal -0.019597     49
Spike   0.023988      2

Diagnostics END_________________________________________________________________________________

### 2023-01-01 -> 2024-12-31

In [483]:
print('Full history')
run_cot_diagnostics(cot_clean, 'SP500', '2023-01-01', '2024-12-31')
print('Diagnostics END_________________________________________________________________________________')

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/2219192598.py:35: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Full history
==================================================
SECTION 1 — DATA QUALITY
==================================================

Rows       : 103
Date Range : 2023-01-03 → 2024-12-24

Expected Weeks : 104
Missing Weeks  : 1
Missing Dates  : [datetime.date(2023, 7, 4)]

Nulls : None ✓

OI Spikes (>2 std devs) : 0

==================================================
SECTION 2 — DESCRIPTIVE STATISTICS
==================================================

--- Actor Net Positions ---

Dealer
  Mean :     -915,943
  Max  :      235,237
  Min  :   -1,886,960
  Std  :      630,948

Asset Manager
  Mean :    1,565,715
  Max  :    2,204,967
  Min  :      508,640
  Std  :      495,546

Lev Money
  Mean :     -645,403
  Max  :     -288,089
  Min  :   -1,099,608
  Std  :      165,911

--- Average Crowding (% of OI) ---
  Dealer              : 30.3%
  Asset Manager       : 43.6%
  Lev Money           : 20.4%

--- Structural Net Check ---
  Total Net Mean :        4,369  (should be near zero)
  Total Net Std  :      195,327

==================================================
SECTION 3 — CORRELATIONS VS PRICE LEVELS
==================================================

Dealer
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.933     0.0000      ✓
  1        -0.931     0.0000      ✓
  2        -0.927     0.0000      ✓
  3        -0.925     0.0000      ✓
  4        -0.919     0.0000      ✓
  5        -0.912     0.0000      ✓
  6        -0.906     0.0000      ✓
  7        -0.903     0.0000      ✓
  8        -0.899     0.0000      ✓
  9        -0.895     0.0000      ✓
  10       -0.889     0.0000      ✓
  11       -0.885     0.0000      ✓
  12       -0.884     0.0000      ✓

Asset Manager
  Lag        Corr     PValue    Sig
  ----------------------------------
  0         0.883     0.0000      ✓
  1         0.876     0.0000      ✓
  2         0.872     0.0000      ✓
  3         0.869     0.0000      ✓
  4         0.868     0.0000      ✓
  5         0.863     0.0000      ✓
  6         0.857     0.0000      ✓
  7         0.851     0.0000      ✓
  8         0.846     0.0000      ✓
  9         0.840     0.0000      ✓
  10        0.831     0.0000      ✓
  11        0.819     0.0000      ✓
  12        0.812     0.0000      ✓

Lev Money
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.068     0.4967
  1        -0.057     0.5717
  2        -0.059     0.5558
  3        -0.050     0.6181
  4        -0.049     0.6305
  5        -0.060     0.5583
  6        -0.081     0.4290
  7        -0.082     0.4271
  8        -0.100     0.3363
  9        -0.097     0.3512
  10       -0.100     0.3408
  11       -0.094     0.3718
  12       -0.087     0.4123

==================================================
SECTION 4 — FORWARD RETURN ANALYSIS
==================================================

Dealer
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.022     0.8322
  Fwd_8wk_Return     -0.007     0.9478
  Fwd_12wk_Return     0.004     0.9662

Asset Manager
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.015     0.8806
  Fwd_8wk_Return     -0.000     0.9984
  Fwd_12wk_Return    -0.083     0.4361

Lev Money
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.068     0.5041
  Fwd_8wk_Return      0.049     0.6344
  Fwd_12wk_Return     0.150     0.1568

==================================================
SECTION 5 — CROWDING REGIME ANALYSIS
==================================================

Lev Money Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0275     0.0518     0.0795     21
  Normal (mid 60%)         0.0181     0.0309     0.0454     62
  Low (bottom 20%)         0.0083     0.0337     0.0652     20

Lev Money Short Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0231     0.0518     0.0670     21
  Normal (mid 60%)         0.0107     0.0194     0.0358     62
  Low (bottom 20%)         0.0352     0.0632     0.0913     20

Asset Mgr Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0141     0.0380     0.0584     21
  Normal (mid 60%)         0.0185     0.0323     0.0527     62
  Low (bottom 20%)         0.0194     0.0410     0.0568     20

Dealer Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0199     0.0334     0.0512     21
  Normal (mid 60%)         0.0182     0.0354     0.0550     62
  Low (bottom 20%)         0.0147     0.0354     0.0559     20

High vs Low Dealer Long — t-stat: 0.547, p-value: 0.5877

--- Low Dealer Long Bucket — OI Spike vs Normal ---
            mean  count
Period
Normal  0.014735     19

Diagnostics END_________________________________________________________________________________

### 2013-06-01 -> 2015-12-30

In [485]:
print('Full history')
run_cot_diagnostics(cot_clean, 'SP500', '2013-06-01', '2015-12-30')
print('Diagnostics END_________________________________________________________________________________')

Full history

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/2219192598.py:35: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

==================================================
SECTION 1 — DATA QUALITY
==================================================

Rows       : 135
Date Range : 2013-06-04 → 2015-12-29

Expected Weeks : 135
Missing Weeks  : 0

Nulls : None ✓

OI Spikes (>2 std devs) : 8
Report_Date_as_MM_DD_YYYY  Open_Interest_All
               2013-06-11            5348252
               2013-06-18            5877840
               2014-03-18            5783344
               2014-06-17            5353682
               2014-09-16            5511724
               2015-08-25            5553043
               2015-09-01            5320358
               2015-09-15            5528100

==================================================
SECTION 2 — DESCRIPTIVE STATISTICS
==================================================

--- Actor Net Positions ---

Dealer
  Mean :     -584,488
  Max  :      323,310
  Min  :     -893,942
  Std  :      319,439

Asset Manager
  Mean :      924,586
  Max  :    1,236,012
  Min  :      207,127
  Std  :      228,903

Lev Money
  Mean :     -408,576
  Max  :      -50,462
  Min  :     -734,366
  Std  :      141,679

--- Average Crowding (% of OI) ---
  Dealer              : 26.2%
  Asset Manager       : 49.9%
  Lev Money           : 36.1%

--- Structural Net Check ---
  Total Net Mean :      -68,479  (should be near zero)
  Total Net Std  :      115,377

==================================================
SECTION 3 — CORRELATIONS VS PRICE LEVELS
==================================================

Dealer
  Lag        Corr     PValue    Sig
  ----------------------------------
  0         0.455     0.0000      ✓
  1         0.457     0.0000      ✓
  2         0.459     0.0000      ✓
  3         0.460     0.0000      ✓
  4         0.465     0.0000      ✓
  5         0.466     0.0000      ✓
  6         0.463     0.0000      ✓
  7         0.454     0.0000      ✓
  8         0.438     0.0000      ✓
  9         0.426     0.0000      ✓
  10        0.416     0.0000      ✓
  11        0.400     0.0000      ✓
  12        0.394     0.0000      ✓

Asset Manager
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.269     0.0016      ✓
  1        -0.293     0.0006      ✓
  2        -0.307     0.0003      ✓
  3        -0.303     0.0004      ✓
  4        -0.299     0.0005      ✓
  5        -0.305     0.0004      ✓
  6        -0.308     0.0004      ✓
  7        -0.296     0.0007      ✓
  8        -0.289     0.0010      ✓
  9        -0.291     0.0010      ✓
  10       -0.282     0.0015      ✓
  11       -0.274     0.0021      ✓
  12       -0.259     0.0038      ✓

Lev Money
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.180     0.0362      ✓
  1        -0.182     0.0356      ✓
  2        -0.185     0.0329      ✓
  3        -0.206     0.0176      ✓
  4        -0.221     0.0110      ✓
  5        -0.223     0.0106      ✓
  6        -0.224     0.0106      ✓
  7        -0.217     0.0140      ✓
  8        -0.200     0.0244      ✓
  9        -0.187     0.0359      ✓
  10       -0.169     0.0594
  11       -0.139     0.1250
  12       -0.146     0.1075

==================================================
SECTION 4 — FORWARD RETURN ANALYSIS
==================================================

Dealer
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.004     0.9625
  Fwd_8wk_Return     -0.026     0.7702
  Fwd_12wk_Return    -0.103     0.2553

Asset Manager
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.133     0.1312
  Fwd_8wk_Return     -0.157     0.0777
  Fwd_12wk_Return    -0.139     0.1242

Lev Money
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.003     0.9703
  Fwd_8wk_Return      0.030     0.7401
  Fwd_12wk_Return     0.069     0.4489

==================================================
SECTION 5 — CROWDING REGIME ANALYSIS
==================================================

Lev Money Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0059     0.0223     0.0291     27
  Normal (mid 60%)         0.0062     0.0109     0.0203     82
  Low (bottom 20%)         0.0149     0.0236     0.0222     26

Lev Money Short Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0160     0.0193     0.0181     27
  Normal (mid 60%)         0.0023     0.0093     0.0186     82
  Low (bottom 20%)         0.0173     0.0317     0.0409     26

Asset Mgr Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)         -0.0004     0.0150     0.0179     27
  Normal (mid 60%)         0.0092     0.0101     0.0199     82
  Low (bottom 20%)         0.0115     0.0368     0.0395     26

Dealer Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)         -0.0021     0.0106     0.0208     27
  Normal (mid 60%)         0.0076     0.0115     0.0155     82
  Low (bottom 20%)         0.0164     0.0309     0.0456     26

High vs Low Dealer Long — t-stat: -1.718, p-value: 0.0924

--- Low Dealer Long Bucket — OI Spike vs Normal ---
            mean  count
Period
Normal  0.016500     25
Spike   0.014802      1

Diagnostics END_________________________________________________________________________________

# Diagnosics

In [422]:

df = run_cot_diagnostics(cot_clean, 'SP500', '2010-01-01', '2025-12-31')

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_28852/2219192598.py:35: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

==================================================
SECTION 1 — DATA QUALITY
==================================================

Rows       : 798
Date Range : 2010-07-20 → 2025-12-30

Expected Weeks : 807
Missing Weeks  : 9
Missing Dates  : [datetime.date(2012, 10, 30), datetime.date(2012, 12, 25), datetime.date(2013, 1, 1), datetime.date(2017, 7, 4), datetime.date(2018, 12, 25), datetime.date(2019, 1, 1), datetime.date(2020, 12, 22), datetime.date(2023, 7, 4), datetime.date(2025, 11, 11)]

Nulls : None ✓

OI Spikes (>2 std devs) : 41
Report_Date_as_MM_DD_YYYY  Open_Interest_All
               2020-03-17            8622736
               2023-05-02            6526923
               2023-05-09            6607327
               2023-05-16            6668927
               2023-05-23            6749811
               2023-05-30            6945040
               2023-06-06            7055301
               2023-06-13            8170247
               2023-07-18            6707667
               2023-08-29            6486374
               2023-09-12            6966110
               2023-09-26            6496171
               2023-10-03            6550685
               2023-10-24            6474351
               2023-10-31            6503266
               2023-11-07            6523739
               2023-11-14            6875964
               2023-11-21            6853709
               2023-11-28            6893768
               2023-12-05            6974635
               2023-12-12            7931741
               2024-01-30            6689456
               2024-02-06            6643489
               2024-02-13            6933764
               2024-02-20            6728892
               2024-02-27            7160472
               2024-03-05            7192032
               2024-03-12            8193256
               2024-04-16            6468666
               2024-06-11            6623813
               2024-06-18            7598493
               2024-08-06            6771465
               2024-09-17            7324339
               2024-11-12            6560325
               2024-12-10            6566543
               2024-12-17            7141865
               2025-03-11            6704628
               2025-03-18            6989524
               2025-04-08            7749237
               2025-06-17            6689971
               2025-09-16            6667424

==================================================
SECTION 2 — DESCRIPTIVE STATISTICS
==================================================

--- Actor Net Positions ---

Dealer
  Mean :     -559,458
  Max  :      467,419
  Min  :   -1,886,960
  Std  :      461,474

Asset Manager
  Mean :      984,453
  Max  :    2,204,967
  Min  :      200,873
  Std  :      444,603

Lev Money
  Mean :     -390,907
  Max  :      103,287
  Min  :   -1,099,608
  Std  :      208,526

--- Average Crowding (% of OI) ---
  Dealer              : 26.4%
  Asset Manager       : 53.0%
  Lev Money           : 26.8%

--- Structural Net Check ---
  Total Net Mean :       34,087  (should be near zero)
  Total Net Std  :      192,744

==================================================
SECTION 3 — CORRELATIONS VS PRICE LEVELS
==================================================

Dealer
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.452     0.0000      ✓
  1        -0.448     0.0000      ✓
  2        -0.445     0.0000      ✓
  3        -0.441     0.0000      ✓
  4        -0.437     0.0000      ✓
  5        -0.435     0.0000      ✓
  6        -0.432     0.0000      ✓
  7        -0.429     0.0000      ✓
  8        -0.428     0.0000      ✓
  9        -0.426     0.0000      ✓
  10       -0.425     0.0000      ✓
  11       -0.423     0.0000      ✓
  12       -0.421     0.0000      ✓

Asset Manager
  Lag        Corr     PValue    Sig
  ----------------------------------
  0         0.564     0.0000      ✓
  1         0.560     0.0000      ✓
  2         0.557     0.0000      ✓
  3         0.554     0.0000      ✓
  4         0.551     0.0000      ✓
  5         0.547     0.0000      ✓
  6         0.544     0.0000      ✓
  7         0.542     0.0000      ✓
  8         0.539     0.0000      ✓
  9         0.537     0.0000      ✓
  10        0.534     0.0000      ✓
  11        0.531     0.0000      ✓
  12        0.528     0.0000      ✓

Lev Money
  Lag        Corr     PValue    Sig
  ----------------------------------
  0        -0.300     0.0000      ✓
  1        -0.297     0.0000      ✓
  2        -0.294     0.0000      ✓
  3        -0.290     0.0000      ✓
  4        -0.285     0.0000      ✓
  5        -0.279     0.0000      ✓
  6        -0.276     0.0000      ✓
  7        -0.272     0.0000      ✓
  8        -0.268     0.0000      ✓
  9        -0.263     0.0000      ✓
  10       -0.258     0.0000      ✓
  11       -0.254     0.0000      ✓
  12       -0.249     0.0000      ✓

==================================================
SECTION 4 — FORWARD RETURN ANALYSIS
==================================================

Dealer
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return      0.033     0.3599
  Fwd_8wk_Return      0.018     0.6091
  Fwd_12wk_Return    -0.003     0.9278

Asset Manager
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.037     0.2969
  Fwd_8wk_Return     -0.041     0.2511
  Fwd_12wk_Return    -0.036     0.3156

Lev Money
  Horizon              Corr     PValue    Sig
  ------------------------------------------
  Fwd_4wk_Return     -0.022     0.5383
  Fwd_8wk_Return     -0.024     0.4967
  Fwd_12wk_Return    -0.035     0.3241

==================================================
SECTION 5 — CROWDING REGIME ANALYSIS
==================================================

Lev Money Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0113     0.0236     0.0357    160
  Normal (mid 60%)         0.0086     0.0175     0.0242    479
  Low (bottom 20%)         0.0130     0.0243     0.0418    159

Lev Money Short Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0067     0.0141     0.0208    160
  Normal (mid 60%)         0.0104     0.0199     0.0315    479
  Low (bottom 20%)         0.0122     0.0268     0.0349    159

Asset Mgr Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0051     0.0088     0.0126    160
  Normal (mid 60%)         0.0112     0.0219     0.0324    479
  Low (bottom 20%)         0.0113     0.0260     0.0398    159

Dealer Long Crowding Regimes
  Regime                  4wk Ret    8wk Ret   12wk Ret      N
  ----------------------------------------------------------
  High  (top 20%)          0.0167     0.0312     0.0421    160
  Normal (mid 60%)         0.0096     0.0194     0.0269    479
  Low (bottom 20%)         0.0042     0.0108     0.0269    159

High vs Low Dealer Long — t-stat: 2.580, p-value: 0.0103

--- Low Dealer Long Bucket — OI Spike vs Normal ---
            mean  count
Period
Normal  0.003256    146
Spike   0.017347     11

# Robustness Tests

In [463]:
run_robustness_tests(df)

============================================================
ROBUSTNESS & INVESTIGATIVE ANALYSIS
Instrument : SP500
Period     : 2010-07-20 → 2025-12-30
============================================================

============================================================
TEST 9 — COMPOSITE SIGNAL BACKTEST
Regime filter — accumulation vs distribution phase
============================================================

--- Weekly Signal Terciles (for reference) ---
  Tercile       4wk Ret    8wk Ret   12wk Ret      N
  --------------------------------------------------
  Low            0.0100     0.0277     0.0429    108
  Mid            0.0122     0.0226     0.0359     99
  High           0.0106     0.0147     0.0262    103

  High vs Low — t-stat: 0.077, p-value: 0.9386

--- Regime Filter (12-week rolling positioning) ---

  Regime        4wk Ret    8wk Ret   12wk Ret      N
  --------------------------------------------------
  Bullish        0.0123     0.0243     0.0375    116
  Neutral        0.0066     0.0168     0.0417     52
  Bearish        0.0114     0.0216     0.0309    142

  Bullish vs Bearish — t-stat: 0.158, p-value: 0.8744

  Regime Distribution:
Regime
Bearish    142
Bullish    116
Neutral     52