In [2]:
import yfinance as yf
import pandas as pd

import datetime as dt
from datetime import timedelta

In [ ]:
import yfinance as yf
import pandas as pd

import datetime as dt
from datetime import timedelta


TICKER_DICTIONARY = {

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 1: REGIONS
    # ══════════════════════════════════════════════════════════════════
    'VOO':    {'label': 'US',            'category': 'stocks', 'level': 1, 'weight': 200},
    'QQQ':    {'label': 'Nasdaq 100',    'category': 'stocks', 'level': 1, 'weight': 180},
    'IWM':    {'label': 'US Small Cap',  'category': 'stocks', 'level': 1, 'weight': 70},
    'EWJ':    {'label': 'Japan',         'category': 'stocks', 'level': 1, 'weight': 70},
    'FXI':    {'label': 'China',         'category': 'stocks', 'level': 1, 'weight': 70},
    'EWG':    {'label': 'Germany',       'category': 'stocks', 'level': 1, 'weight': 60},
    'EWU':    {'label': 'UK',            'category': 'stocks', 'level': 1, 'weight': 60},
    'INDA':   {'label': 'India',         'category': 'stocks', 'level': 1, 'weight': 60},
    'EWT':    {'label': 'Taiwan',        'category': 'stocks', 'level': 1, 'weight': 50},
    'EWZ':    {'label': 'Brazil',        'category': 'stocks', 'level': 1, 'weight': 50},
    'EZA':    {'label': 'South Africa',  'category': 'stocks', 'level': 1, 'weight': 40},
    'EWA':    {'label': 'Australia',     'category': 'stocks', 'level': 1, 'weight': 40},
    'EWY':    {'label': 'South Korea',   'category': 'stocks', 'level': 1, 'weight': 45},
    'EWC':    {'label': 'Canada',        'category': 'stocks', 'level': 1, 'weight': 45},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 2: US SECTORS (parent = VOO)
    # ══════════════════════════════════════════════════════════════════
    'XLK':    {'label': 'Technology',       'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 150},
    'XLF':    {'label': 'Financials',       'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 100},
    'XLV':    {'label': 'Healthcare',       'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 90},
    'XLY':    {'label': 'Consumer Disc',    'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 80},
    'XLP':    {'label': 'Consumer Staples', 'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 60},
    'XLE':    {'label': 'Energy',           'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 70},
    'XLI':    {'label': 'Industrials',      'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 70},
    'XLC':    {'label': 'Communication',    'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 60},
    'XLU':    {'label': 'Utilities',        'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 40},
    'XLRE':   {'label': 'Real Estate',      'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 35},
    'XLB':    {'label': 'Materials',        'category': 'stocks', 'level': 2, 'parent': 'VOO', 'weight': 35},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: TECHNOLOGY STOCKS (parent = XLK)
    # ══════════════════════════════════════════════════════════════════
    'NVDA':   {'label': 'Nvidia',        'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 150},
    'AAPL':   {'label': 'Apple',         'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 140},
    'MSFT':   {'label': 'Microsoft',     'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 140},
    'AVGO':   {'label': 'Broadcom',      'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 90},
    'AMD':    {'label': 'AMD',           'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 70},
    'ADBE':   {'label': 'Adobe',         'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 55},
    'CRM':    {'label': 'Salesforce',    'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 55},
    'ORCL':   {'label': 'Oracle',        'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 50},
    'INTC':   {'label': 'Intel',         'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 40},
    'CSCO':   {'label': 'Cisco',         'category': 'stocks', 'level': 3, 'parent': 'XLK', 'weight': 40},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: FINANCIALS (parent = XLF)
    # ══════════════════════════════════════════════════════════════════
    'BRK-B':  {'label': 'Berkshire',      'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 90},
    'JPM':    {'label': 'JPMorgan',       'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 80},
    'V':      {'label': 'Visa',           'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 70},
    'MA':     {'label': 'Mastercard',     'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 65},
    'GS':     {'label': 'Goldman Sachs',  'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 60},
    'MS':     {'label': 'Morgan Stanley', 'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 50},
    'BAC':    {'label': 'Bank of America','category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 50},
    'WFC':    {'label': 'Wells Fargo',    'category': 'stocks', 'level': 3, 'parent': 'XLF', 'weight': 40},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: HEALTHCARE (parent = XLV)
    # ══════════════════════════════════════════════════════════════════
    'LLY':    {'label': 'Eli Lilly',      'category': 'stocks', 'level': 3, 'parent': 'XLV', 'weight': 80},
    'UNH':    {'label': 'UnitedHealth',   'category': 'stocks', 'level': 3, 'parent': 'XLV', 'weight': 75},
    'JNJ':    {'label': 'J&J',            'category': 'stocks', 'level': 3, 'parent': 'XLV', 'weight': 60},
    'ABBV':   {'label': 'AbbVie',         'category': 'stocks', 'level': 3, 'parent': 'XLV', 'weight': 55},
    'PFE':    {'label': 'Pfizer',         'category': 'stocks', 'level': 3, 'parent': 'XLV', 'weight': 40},
    'MRK':    {'label': 'Merck',          'category': 'stocks', 'level': 3, 'parent': 'XLV', 'weight': 50},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: CONSUMER DISCRETIONARY (parent = XLY)
    # ══════════════════════════════════════════════════════════════════
    'AMZN':   {'label': 'Amazon',         'category': 'stocks', 'level': 3, 'parent': 'XLY', 'weight': 130},
    'TSLA':   {'label': 'Tesla',          'category': 'stocks', 'level': 3, 'parent': 'XLY', 'weight': 100},
    'HD':     {'label': 'Home Depot',     'category': 'stocks', 'level': 3, 'parent': 'XLY', 'weight': 55},
    'MCD':    {'label': 'McDonalds',      'category': 'stocks', 'level': 3, 'parent': 'XLY', 'weight': 50},
    'NKE':    {'label': 'Nike',           'category': 'stocks', 'level': 3, 'parent': 'XLY', 'weight': 40},
    'NFLX':   {'label': 'Netflix',        'category': 'stocks', 'level': 3, 'parent': 'XLY', 'weight': 65},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: CONSUMER STAPLES (parent = XLP)
    # ══════════════════════════════════════════════════════════════════
    'PG':     {'label': 'Procter & Gamble','category': 'stocks', 'level': 3, 'parent': 'XLP', 'weight': 60},
    'KO':     {'label': 'Coca-Cola',       'category': 'stocks', 'level': 3, 'parent': 'XLP', 'weight': 55},
    'PEP':    {'label': 'PepsiCo',         'category': 'stocks', 'level': 3, 'parent': 'XLP', 'weight': 50},
    'COST':   {'label': 'Costco',          'category': 'stocks', 'level': 3, 'parent': 'XLP', 'weight': 60},
    'WMT':    {'label': 'Walmart',         'category': 'stocks', 'level': 3, 'parent': 'XLP', 'weight': 55},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: ENERGY (parent = XLE)
    # ══════════════════════════════════════════════════════════════════
    'XOM':    {'label': 'Exxon',          'category': 'stocks', 'level': 3, 'parent': 'XLE', 'weight': 70},
    'CVX':    {'label': 'Chevron',        'category': 'stocks', 'level': 3, 'parent': 'XLE', 'weight': 60},
    'COP':    {'label': 'ConocoPhillips', 'category': 'stocks', 'level': 3, 'parent': 'XLE', 'weight': 45},
    'SLB':    {'label': 'Schlumberger',   'category': 'stocks', 'level': 3, 'parent': 'XLE', 'weight': 35},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: INDUSTRIALS (parent = XLI)
    # ══════════════════════════════════════════════════════════════════
    'CAT':    {'label': 'Caterpillar',    'category': 'stocks', 'level': 3, 'parent': 'XLI', 'weight': 55},
    'GE':     {'label': 'GE Aerospace',   'category': 'stocks', 'level': 3, 'parent': 'XLI', 'weight': 55},
    'UPS':    {'label': 'UPS',            'category': 'stocks', 'level': 3, 'parent': 'XLI', 'weight': 40},
    'BA':     {'label': 'Boeing',         'category': 'stocks', 'level': 3, 'parent': 'XLI', 'weight': 45},
    'HON':    {'label': 'Honeywell',      'category': 'stocks', 'level': 3, 'parent': 'XLI', 'weight': 40},
    'LMT':    {'label': 'Lockheed Martin','category': 'stocks', 'level': 3, 'parent': 'XLI', 'weight': 45},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: COMMUNICATION (parent = XLC)
    # ══════════════════════════════════════════════════════════════════
    'META':   {'label': 'Meta',           'category': 'stocks', 'level': 3, 'parent': 'XLC', 'weight': 110},
    'GOOG':   {'label': 'Alphabet',       'category': 'stocks', 'level': 3, 'parent': 'XLC', 'weight': 120},
    'DIS':    {'label': 'Disney',         'category': 'stocks', 'level': 3, 'parent': 'XLC', 'weight': 50},
    'CMCSA':  {'label': 'Comcast',        'category': 'stocks', 'level': 3, 'parent': 'XLC', 'weight': 35},
    'TMUS':   {'label': 'T-Mobile',       'category': 'stocks', 'level': 3, 'parent': 'XLC', 'weight': 40},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: UTILITIES (parent = XLU)
    # ══════════════════════════════════════════════════════════════════
    'NEE':    {'label': 'NextEra Energy', 'category': 'stocks', 'level': 3, 'parent': 'XLU', 'weight': 45},
    'DUK':    {'label': 'Duke Energy',    'category': 'stocks', 'level': 3, 'parent': 'XLU', 'weight': 35},
    'SO':     {'label': 'Southern Co',    'category': 'stocks', 'level': 3, 'parent': 'XLU', 'weight': 35},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: REAL ESTATE (parent = XLRE)
    # ══════════════════════════════════════════════════════════════════
    'AMT':    {'label': 'American Tower', 'category': 'stocks', 'level': 3, 'parent': 'XLRE', 'weight': 40},
    'PLD':    {'label': 'Prologis',       'category': 'stocks', 'level': 3, 'parent': 'XLRE', 'weight': 40},
    'SPG':    {'label': 'Simon Property', 'category': 'stocks', 'level': 3, 'parent': 'XLRE', 'weight': 30},

    # ══════════════════════════════════════════════════════════════════
    # EQUITIES — LEVEL 3: MATERIALS (parent = XLB)
    # ══════════════════════════════════════════════════════════════════
    'LIN':    {'label': 'Linde',          'category': 'stocks', 'level': 3, 'parent': 'XLB', 'weight': 45},
    'APD':    {'label': 'Air Products',   'category': 'stocks', 'level': 3, 'parent': 'XLB', 'weight': 30},
    'SHW':    {'label': 'Sherwin-Williams','category': 'stocks', 'level': 3, 'parent': 'XLB', 'weight': 35},

    # ══════════════════════════════════════════════════════════════════
    # FX — LEVEL 1 ONLY
    # ══════════════════════════════════════════════════════════════════
    'EURUSD=X': {'label': 'EUR/USD',      'category': 'fx', 'level': 1, 'weight': 100},
    'GBPUSD=X': {'label': 'GBP/USD',      'category': 'fx', 'level': 1, 'weight': 90},
    'USDJPY=X': {'label': 'USD/JPY',      'category': 'fx', 'level': 1, 'weight': 90},
    'USDCAD=X': {'label': 'USD/CAD',      'category': 'fx', 'level': 1, 'weight': 60},
    'USDCHF=X': {'label': 'USD/CHF',      'category': 'fx', 'level': 1, 'weight': 60},
    'AUDUSD=X': {'label': 'AUD/USD',      'category': 'fx', 'level': 1, 'weight': 50},
    'NZDUSD=X': {'label': 'NZD/USD',      'category': 'fx', 'level': 1, 'weight': 40},
    'USDZAR=X': {'label': 'USD/ZAR',      'category': 'fx', 'level': 1, 'weight': 40},
    'USDCNY=X': {'label': 'USD/CNY',      'category': 'fx', 'level': 1, 'weight': 50},
    'USDMXN=X': {'label': 'USD/MXN',      'category': 'fx', 'level': 1, 'weight': 35},

    # ══════════════════════════════════════════════════════════════════
    # CRYPTO — LEVEL 1 ONLY
    # ══════════════════════════════════════════════════════════════════
    'BTC-USD':  {'label': 'Bitcoin',      'category': 'crypto', 'level': 1, 'weight': 200},
    'ETH-USD':  {'label': 'Ethereum',     'category': 'crypto', 'level': 1, 'weight': 120},
    'SOL-USD':  {'label': 'Solana',       'category': 'crypto', 'level': 1, 'weight': 70},
    'XRP-USD':  {'label': 'XRP',          'category': 'crypto', 'level': 1, 'weight': 60},
    'BNB-USD':  {'label': 'BNB',          'category': 'crypto', 'level': 1, 'weight': 50},
    'ADA-USD':  {'label': 'Cardano',      'category': 'crypto', 'level': 1, 'weight': 40},
    'DOGE-USD': {'label': 'Dogecoin',     'category': 'crypto', 'level': 1, 'weight': 35},
    'AVAX-USD': {'label': 'Avalanche',    'category': 'crypto', 'level': 1, 'weight': 30},
    'DOT-USD':  {'label': 'Polkadot',     'category': 'crypto', 'level': 1, 'weight': 25},
    'LINK-USD': {'label': 'Chainlink',    'category': 'crypto', 'level': 1, 'weight': 25},

    # ══════════════════════════════════════════════════════════════════
    # COMMODITIES — LEVEL 1 ONLY
    # ══════════════════════════════════════════════════════════════════
    'GC=F':   {'label': 'Gold',           'category': 'commodities', 'level': 1, 'weight': 120},
    'SI=F':   {'label': 'Silver',         'category': 'commodities', 'level': 1, 'weight': 60},
    'CL=F':   {'label': 'WTI Crude',      'category': 'commodities', 'level': 1, 'weight': 110},
    'BZ=F':   {'label': 'Brent Crude',    'category': 'commodities', 'level': 1, 'weight': 100},
    'NG=F':   {'label': 'Natural Gas',    'category': 'commodities', 'level': 1, 'weight': 70},
    'HG=F':   {'label': 'Copper',         'category': 'commodities', 'level': 1, 'weight': 60},
    'PL=F':   {'label': 'Platinum',       'category': 'commodities', 'level': 1, 'weight': 35},
    'ZC=F':   {'label': 'Corn',           'category': 'commodities', 'level': 1, 'weight': 40},
    'ZS=F':   {'label': 'Soybeans',       'category': 'commodities', 'level': 1, 'weight': 40},
    'ZW=F':   {'label': 'Wheat',          'category': 'commodities', 'level': 1, 'weight': 35},
    'KC=F':   {'label': 'Coffee',         'category': 'commodities', 'level': 1, 'weight': 35},
    'CT=F':   {'label': 'Cotton',         'category': 'commodities', 'level': 1, 'weight': 25},

    # ══════════════════════════════════════════════════════════════════
    # BONDS — LEVEL 1 ONLY
    # ══════════════════════════════════════════════════════════════════
    'TLT':    {'label': 'US 20Y+',        'category': 'bonds', 'level': 1, 'weight': 100},
    'IEF':    {'label': 'US 7-10Y',       'category': 'bonds', 'level': 1, 'weight': 80},
    'SHY':    {'label': 'US 1-3Y',        'category': 'bonds', 'level': 1, 'weight': 60},
    'LQD':    {'label': 'IG Corporate',   'category': 'bonds', 'level': 1, 'weight': 60},
    'HYG':    {'label': 'High Yield',     'category': 'bonds', 'level': 1, 'weight': 50},
    'EMB':    {'label': 'EM Debt',        'category': 'bonds', 'level': 1, 'weight': 50},
    'MBB':    {'label': 'Mortgage',       'category': 'bonds', 'level': 1, 'weight': 40},
    'TIP':    {'label': 'TIPS',           'category': 'bonds', 'level': 1, 'weight': 40},
    'IGLT.L': {'label': 'UK Gilts',       'category': 'bonds', 'level': 1, 'weight': 40},
    'SDEU.L': {'label': 'Euro Govt',      'category': 'bonds', 'level': 1, 'weight': 40},
    '1482.T': {'label': 'Japan Govt',     'category': 'bonds', 'level': 1, 'weight': 35},
}

TIMEFRAME_DAYS = {
    "1D": 1,
    "1W": 5,
    "1M": 21,
    "3M": 63,
    "1Y": 252,
    "2Y": 504,
    "5Y": 1260,
}


def download_and_save_csv():
    c

In [8]:
current_date = dt.datetime.now().date()

date_5_years_ago = current_date- timedelta(days=1850)
df = yf.download(list(TICKER_DICTIONARY.keys()),start =date_5_years_ago )['Close']


df

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_41845/2710565963.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(list(TICKER_DICTIONARY.keys()),start =date_5_years_ago )['Close']
[*********************100%***********************]  127 of 127 completed

Ticker,1482.T,AAPL,ABBV,ADA-USD,ADBE,AMD,AMT,AMZN,APD,AUDUSD=X,...,XLP,XLRE,XLU,XLV,XLY,XOM,XRP-USD,ZC=F,ZS=F,ZW=F
Date,,,,,,,,,,,,,,,,,,,,,
2021-03-23,2038.619629,119.353409,86.583031,1.121552,460.200012,78.379997,196.508286,156.875000,241.157867,0.774550,...,58.738075,32.899578,26.877895,105.641914,79.553024,45.594402,0.556595,551.25,1423.25,634.75
2021-03-24,2052.660645,116.967125,85.113022,1.075002,451.510010,76.480003,194.071671,154.353500,244.072540,0.760470,...,58.510120,32.755432,26.886486,105.521980,78.376831,46.519169,0.488837,553.25,1432.75,624.75
2021-03-25,2050.906006,117.454124,85.790215,1.101574,450.989990,76.220001,194.259750,152.313004,243.422867,0.759100,...,59.079967,33.035252,27.174295,105.964851,79.063347,46.387066,0.517498,546.50,1414.25,612.50
2021-03-26,2049.150635,118.058022,87.524529,1.213969,469.089996,77.410004,204.177094,152.601501,252.158264,0.759400,...,60.123238,33.840778,27.264503,107.966965,79.721046,47.650364,0.567055,552.50,1400.50,613.25
2021-03-27,NaN,NaN,NaN,1.176577,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.550443,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-11,NaN,NaN,NaN,0.249663,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.355449,NaN,NaN,NaN
2026-04-12,NaN,NaN,NaN,0.236272,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.324998,NaN,NaN,NaN
2026-04-13,1586.000000,259.200012,206.470001,0.248573,240.110001,246.830002,179.150009,239.889999,298.649994,0.701990,...,81.550003,43.020000,46.389999,147.970001,113.919998,152.639999,1.376666,440.25,1162.25,582.25
2026-04-14,1594.000000,258.829987,210.259995,0.239667,235.720001,255.070007,176.410004,249.020004,296.630005,0.709930,...,81.470001,43.430000,46.470001,148.830002,116.440002,149.240005,1.361828,443.00,1158.00,592.00
2026-04-15,1597.000000,266.429993,208.419998,0.249700,244.660004,258.119995,176.990005,248.500000,295.209991,0.717273,...,81.059998,43.410000,46.020000,147.770004,118.180000,149.009995,1.401300,451.75,1165.25,600.50

In [9]:
df = df.ffill()
df

Ticker,1482.T,AAPL,ABBV,ADA-USD,ADBE,AMD,AMT,AMZN,APD,AUDUSD=X,...,XLP,XLRE,XLU,XLV,XLY,XOM,XRP-USD,ZC=F,ZS=F,ZW=F
Date,,,,,,,,,,,,,,,,,,,,,
2021-03-23,2038.619629,119.353409,86.583031,1.121552,460.200012,78.379997,196.508286,156.875000,241.157867,0.774550,...,58.738075,32.899578,26.877895,105.641914,79.553024,45.594402,0.556595,551.25,1423.25,634.75
2021-03-24,2052.660645,116.967125,85.113022,1.075002,451.510010,76.480003,194.071671,154.353500,244.072540,0.760470,...,58.510120,32.755432,26.886486,105.521980,78.376831,46.519169,0.488837,553.25,1432.75,624.75
2021-03-25,2050.906006,117.454124,85.790215,1.101574,450.989990,76.220001,194.259750,152.313004,243.422867,0.759100,...,59.079967,33.035252,27.174295,105.964851,79.063347,46.387066,0.517498,546.50,1414.25,612.50
2021-03-26,2049.150635,118.058022,87.524529,1.213969,469.089996,77.410004,204.177094,152.601501,252.158264,0.759400,...,60.123238,33.840778,27.264503,107.966965,79.721046,47.650364,0.567055,552.50,1400.50,613.25
2021-03-27,2049.150635,118.058022,87.524529,1.176577,469.089996,77.410004,204.177094,152.601501,252.158264,0.759400,...,60.123238,33.840778,27.264503,107.966965,79.721046,47.650364,0.550443,552.50,1400.50,613.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-11,1576.000000,260.480011,207.940002,0.249663,225.350006,245.039993,177.516327,238.380005,298.709991,0.707570,...,82.370003,42.820000,46.959999,147.309998,112.889999,152.509995,1.355449,441.00,1175.75,571.00
2026-04-12,1576.000000,260.480011,207.940002,0.236272,225.350006,245.039993,177.516327,238.380005,298.709991,0.707570,...,82.370003,42.820000,46.959999,147.309998,112.889999,152.509995,1.324998,441.00,1175.75,571.00
2026-04-13,1586.000000,259.200012,206.470001,0.248573,240.110001,246.830002,179.150009,239.889999,298.649994,0.701990,...,81.550003,43.020000,46.389999,147.970001,113.919998,152.639999,1.376666,440.25,1162.25,582.25
2026-04-14,1594.000000,258.829987,210.259995,0.239667,235.720001,255.070007,176.410004,249.020004,296.630005,0.709930,...,81.470001,43.430000,46.470001,148.830002,116.440002,149.240005,1.361828,443.00,1158.00,592.00
2026-04-15,1597.000000,266.429993,208.419998,0.249700,244.660004,258.119995,176.990005,248.500000,295.209991,0.717273,...,81.059998,43.410000,46.020000,147.770004,118.180000,149.009995,1.401300,451.75,1165.25,600.50

In [15]:
returns_dict = {}
last_price = df.iloc[-1]
for tf, days in TIMEFRAME_DAYS.items():
    print(days)
    return_for_tf = ((last_price - df.iloc[-days-1]) / df.iloc[-days-1]) * 100
    returns_dict[tf] = return_for_tf

returns_df = pd.DataFrame(returns_dict)
returns_df

1
5
21
63
252
504
1260

,1D,1W,1M,3M,1Y,2Y,5Y
Ticker,,,,,,,
1482.T,0.188206,1.332487,0.826457,-0.293838,0.146945,1.126499,-5.038656
AAPL,2.936293,2.284237,5.466708,-3.292199,25.318062,14.027766,86.962370
ABBV,-0.875105,0.230834,0.598516,-5.645344,7.800047,18.769430,62.259290
ADA-USD,4.186224,-1.793052,-7.623557,-2.289945,-66.338364,-75.358860,-35.323617
ADBE,3.792636,8.568892,3.123289,-4.860787,-29.211270,-52.371125,-18.776973
...,...,...,...,...,...,...,...
XOM,-0.154122,-2.294932,-8.728409,-3.572125,43.388658,32.167698,52.944471
XRP-USD,2.898456,3.294541,-0.914841,2.432786,-53.163356,-4.855481,210.796354
ZC=F,1.975169,2.437642,-3.317282,5.672515,18.959842,8.659050,-34.290909
ZS=F,0.626079,-0.893047,-0.554726,3.669929,21.190848,17.850822,-19.079861
ZW=F,1.435811,5.166375,0.460059,11.772918,18.092429,11.668991,-29.018913

In [16]:
meta_df = pd.DataFrame.from_dict(TICKER_DICTIONARY, orient='index')

In [17]:
result = meta_df.merge(returns_df, left_index=True, right_index=True)
result

,label,category,level,weight,parent,1D,1W,1M,3M,1Y,2Y,5Y
VOO,US,stocks,1,200,NaN,0.798941,3.017937,6.574839,1.434926,11.608388,19.064996,96.192641
QQQ,Nasdaq 100,stocks,1,180,NaN,1.399944,4.308838,8.434558,4.092860,12.770003,27.147198,145.131643
IWM,US Small Cap,stocks,1,70,NaN,0.249335,3.096069,6.977209,1.856651,23.114915,13.598004,58.612662
EWJ,Japan,stocks,1,70,NaN,-0.380275,1.066609,5.097345,-5.214432,21.534508,39.372020,94.897396
FXI,China,stocks,1,70,NaN,-0.027103,1.737934,2.444447,-6.561946,-1.348698,26.598905,84.793180
...,...,...,...,...,...,...,...,...,...,...,...,...
MBB,Mortgage,bonds,1,40,NaN,-0.199039,0.315884,0.923987,0.250787,4.444301,8.077173,20.426365
TIP,TIPS,bonds,1,40,NaN,-0.089661,0.369306,1.152865,0.559519,2.529170,6.689672,15.058587
IGLT.L,UK Gilts,bonds,1,40,NaN,-0.152288,0.076313,0.229300,-1.329317,1.385993,1.998056,3.979856
SDEU.L,Euro Govt,bonds,1,40,NaN,-0.063441,-0.141419,0.000000,-1.282355,-1.728570,0.971409,1.786238
1482.T,Japan Govt,bonds,1,35,NaN,0.188206,1.332487,0.826457,-0.293838,0.146945,1.126499,-5.038656

In [18]:
result.to_csv('heatmap_data.csv')

In [10]:

returns_dict = {}
last_price = df.iloc[-1]
for tf, days in TIMEFRAME_DAYS.items():
    print(days)
    return_for_tf = ((last_price - df.iloc[-days-1]) / df.iloc[-days-1]) * 100
    returns_dict[tf] = return_for_tf

returns_df = pd.DataFrame(returns_dict)


meta_df = pd.DataFrame.from_dict(TICKER_DICTIONARY, orient='index')


result = meta_df.merge(returns_df, left_index=True, right_index=True)
result.to_csv('heatmap_data.csv')

1
5
21
63
252
504
1260

In [3]:
download_and_save_csv()

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_41845/1409125915.py:221: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(list(TICKER_DICTIONARY.keys()),start =date_5_years_ago )['Close']
[*********************100%***********************]  127 of 127 completed

1
5
21
63
252
504
1260

In [5]:
CSV_PATH = 'heatmap_data.csv'
df = pd.read_csv(CSV_PATH)
df

,Unnamed: 0,label,category,level,weight,parent,1D,1W,1M,3M,1Y,2Y,5Y
0,VOO,US,stocks,1,200,NaN,0.798941,3.017937,6.574839,1.434926,11.608388,19.064996,96.192659
1,QQQ,Nasdaq 100,stocks,1,180,NaN,1.399944,4.308838,8.434558,4.092860,12.770003,27.147190,145.131701
2,IWM,US Small Cap,stocks,1,70,NaN,0.249335,3.096069,6.977209,1.856651,23.114923,13.597996,58.612634
3,EWJ,Japan,stocks,1,70,NaN,-0.380275,1.066609,5.097345,-5.214432,21.534508,39.372012,94.897412
4,FXI,China,stocks,1,70,NaN,-0.027103,1.737934,2.444447,-6.561946,-1.348698,26.598897,84.793180
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,MBB,Mortgage,bonds,1,40,NaN,-0.199039,0.315884,0.923987,0.250787,4.444301,8.077182,20.426365
123,TIP,TIPS,bonds,1,40,NaN,-0.089661,0.369306,1.152865,0.559519,2.529177,6.689664,15.058597
124,IGLT.L,UK Gilts,bonds,1,40,NaN,-0.152288,0.076313,0.229300,-1.329317,1.385993,1.998056,3.979856
125,SDEU.L,Euro Govt,bonds,1,40,NaN,-0.063441,-0.141419,0.000000,-1.282355,-1.728570,0.971416,1.786238
126,1482.T,Japan Govt,bonds,1,35,NaN,0.188206,1.332487,0.826457,-0.293838,0.146952,1.126499,-5.038663

In [7]:
yf.download(['7203.T', '0700.HK', 'RELIANCE.NS', '005930.KS', 'BHP.AX'], period='5d')['Close']

/var/folders/hs/v5c0lrnj61z3tp745vdhh0m40000gn/T/ipykernel_41845/3804074667.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(['7203.T', '0700.HK', 'RELIANCE.NS', '005930.KS', 'BHP.AX'], period='5d')['Close']
[*********************100%***********************]  5 of 5 completed

Ticker      005930.KS     0700.HK  7203.T     BHP.AX  RELIANCE.NS
Date
2026-04-08        NaN         NaN     NaN        NaN  1347.800049
2026-04-09   204000.0  508.500000  3331.0  54.560001  1330.000000
2026-04-10   206000.0  504.500000  3319.0  53.980000  1350.199951
2026-04-13   201000.0  490.000000  3319.0  54.349998  1315.099976
2026-04-14   206500.0  493.200012  3326.0  56.099998          NaN
2026-04-15   211000.0  499.000000  3381.0  56.110001          NaN